/** Beat 4 corroboration rank — generated by scripts/rank-snapshot.ts (npm postingest). Curated Brief/Digest items only; lead pinned. */
import type { MovedRow, RankSnapshot } from "@/lib/corroboration";

export const RANK_CURRENT: RankSnapshot = {
  "schema": 1,
  "at": "2026-10-10T19:18:35.213Z",
  "crawl_at": "2026-10-10T19:18:13Z",
  "lead_id": "hf-incident",
  "rows": [
    {
      "id": "hf-swarm",
      "rank": 1,
      "base_rank": 1,
      "sources": 2,
      "source_keys": [
        "crawl:pub:www.lvivherald.com",
        "x:@dwarkesh_sp"
      ],
      "crawl_hits": [
        "cl:gnews:7ac43f0bffc285af"
      ],
      "mult": 1,
      "lead": true
    },
    {
      "id": "astra-depth",
      "rank": 2,
      "base_rank": 2,
      "sources": 3,
      "source_keys": [
        "crawl:lab:nvidia",
        "x:@amir",
        "x:@steph_palazzolo"
      ],
      "crawl_hits": [
        "cl:rss:nvidia:6e9bdaa4a319db62"
      ],
      "mult": 1.3,
      "lead": false
    },
    {
      "id": "aisle-curl",
      "rank": 3,
      "base_rank": 3,
      "sources": 1,
      "source_keys": [
        "co:aisle"
      ],
      "crawl_hits": [],
      "mult": 1,
      "lead": false
    },
    {
      "id": "harness-papers",
      "rank": 4,
      "base_rank": 4,
      "sources": 1,
      "source_keys": [
        "x:@dair_ai"
      ],
      "crawl_hits": [],
      "mult": 1,
      "lead": false
    }
  ]
};

export const RANK_PREV: RankSnapshot | null = {
  "schema": 1,
  "at": "2026-10-10T18:21:45.031Z",
  "crawl_at": "2026-10-10T18:21:26Z",
  "lead_id": "hf-incident",
  "rows": [
    {
      "id": "hf-swarm",
      "rank": 1,
      "base_rank": 1,
      "sources": 2,
      "source_keys": [
        "crawl:pub:www.lvivherald.com",
        "x:@dwarkesh_sp"
      ],
      "crawl_hits": [
        "cl:gnews:7ac43f0bffc285af"
      ],
      "mult": 1,
      "lead": true
    },
    {
      "id": "astra-depth",
      "rank": 2,
      "base_rank": 2,
      "sources": 3,
      "source_keys": [
        "crawl:lab:nvidia",
        "x:@amir",
        "x:@steph_palazzolo"
      ],
      "crawl_hits": [
        "cl:rss:nvidia:6e9bdaa4a319db62"
      ],
      "mult": 1.3,
      "lead": false
    },
    {
      "id": "aisle-curl",
      "rank": 3,
      "base_rank": 3,
      "sources": 1,
      "source_keys": [
        "co:aisle"
      ],
      "crawl_hits": [],
      "mult": 1,
      "lead": false
    },
    {
      "id": "harness-papers",
      "rank": 4,
      "base_rank": 4,
      "sources": 1,
      "source_keys": [
        "x:@dair_ai"
      ],
      "crawl_hits": [],
      "mult": 1,
      "lead": false
    }
  ]
};

export const RANK_MOVED: MovedRow[] = [
  {
    "id": "hf-swarm",
    "status": "same",
    "prev_rank": 1,
    "rank": 1,
    "prev_sources": 2,
    "sources": 2,
    "by_corroboration": false
  },
  {
    "id": "astra-depth",
    "status": "same",
    "prev_rank": 2,
    "rank": 2,
    "prev_sources": 3,
    "sources": 3,
    "by_corroboration": false
  },
  {
    "id": "aisle-curl",
    "status": "same",
    "prev_rank": 3,
    "rank": 3,
    "prev_sources": 1,
    "sources": 1,
    "by_corroboration": false
  },
  {
    "id": "harness-papers",
    "status": "same",
    "prev_rank": 4,
    "rank": 4,
    "prev_sources": 1,
    "sources": 1,
    "by_corroboration": false
  }
];
