/** Beat 4 corroboration rank — generated by scripts/rank-snapshot.ts (npm postingest). Curated Brief/Digest items only; lead pinned. */
import type { MovedRow, RankSnapshot } from "@/lib/corroboration";

export const RANK_CURRENT: RankSnapshot = {
  "schema": 1,
  "at": "2026-10-04T07:21:43.766Z",
  "crawl_at": "2026-10-04T07:21:32Z",
  "lead_id": "hf-incident",
  "rows": [
    {
      "id": "hf-swarm",
      "rank": 1,
      "base_rank": 1,
      "sources": 1,
      "source_keys": [
        "x:@dwarkesh_sp"
      ],
      "crawl_hits": [],
      "mult": 1,
      "lead": true
    },
    {
      "id": "astra-depth",
      "rank": 2,
      "base_rank": 2,
      "sources": 4,
      "source_keys": [
        "crawl:hn",
        "crawl:lab:nvidia",
        "x:@amir",
        "x:@steph_palazzolo"
      ],
      "crawl_hits": [
        "cl:hn:49943964",
        "cl:hn:49933251",
        "cl:rss:nvidia:6e9bdaa4a319db62"
      ],
      "mult": 1.45,
      "lead": false
    },
    {
      "id": "aisle-curl",
      "rank": 3,
      "base_rank": 3,
      "sources": 1,
      "source_keys": [
        "co:aisle"
      ],
      "crawl_hits": [],
      "mult": 1,
      "lead": false
    },
    {
      "id": "harness-papers",
      "rank": 4,
      "base_rank": 4,
      "sources": 1,
      "source_keys": [
        "x:@dair_ai"
      ],
      "crawl_hits": [],
      "mult": 1,
      "lead": false
    }
  ]
};

export const RANK_PREV: RankSnapshot | null = {
  "schema": 1,
  "at": "2026-10-04T03:15:24.057Z",
  "crawl_at": "2026-10-04T03:14:31Z",
  "lead_id": "hf-incident",
  "rows": [
    {
      "id": "hf-swarm",
      "rank": 1,
      "base_rank": 1,
      "sources": 1,
      "source_keys": [
        "x:@dwarkesh_sp"
      ],
      "crawl_hits": [],
      "mult": 1,
      "lead": true
    },
    {
      "id": "astra-depth",
      "rank": 2,
      "base_rank": 2,
      "sources": 4,
      "source_keys": [
        "crawl:hn",
        "crawl:lab:nvidia",
        "x:@amir",
        "x:@steph_palazzolo"
      ],
      "crawl_hits": [
        "cl:hn:49943964",
        "cl:hn:49933251",
        "cl:rss:nvidia:6e9bdaa4a319db62"
      ],
      "mult": 1.45,
      "lead": false
    },
    {
      "id": "aisle-curl",
      "rank": 3,
      "base_rank": 3,
      "sources": 1,
      "source_keys": [
        "co:aisle"
      ],
      "crawl_hits": [],
      "mult": 1,
      "lead": false
    },
    {
      "id": "harness-papers",
      "rank": 4,
      "base_rank": 4,
      "sources": 1,
      "source_keys": [
        "x:@dair_ai"
      ],
      "crawl_hits": [],
      "mult": 1,
      "lead": false
    }
  ]
};

export const RANK_MOVED: MovedRow[] = [
  {
    "id": "hf-swarm",
    "status": "same",
    "prev_rank": 1,
    "rank": 1,
    "prev_sources": 1,
    "sources": 1,
    "by_corroboration": false
  },
  {
    "id": "astra-depth",
    "status": "same",
    "prev_rank": 2,
    "rank": 2,
    "prev_sources": 4,
    "sources": 4,
    "by_corroboration": false
  },
  {
    "id": "aisle-curl",
    "status": "same",
    "prev_rank": 3,
    "rank": 3,
    "prev_sources": 1,
    "sources": 1,
    "by_corroboration": false
  },
  {
    "id": "harness-papers",
    "status": "same",
    "prev_rank": 4,
    "rank": 4,
    "prev_sources": 1,
    "sources": 1,
    "by_corroboration": false
  }
];
