/** Pass A Digest/Voice unlock — frozen at daily lead pick (or first WROTE after it).
 * Generated by scripts/rank-snapshot.ts / digest tick. Do not edit by hand.
 * Cycle label stays 003. Mid-window crawls must not rewrite this file.
 */
import type { DigestUnlockSnapshot } from "@/lib/digest-unlock";

export const DIGEST_UNLOCK: DigestUnlockSnapshot = {
  "schema": 1,
  "cycleId": "003",
  "pickDate": "2026-10-08",
  "frozenAt": "2026-10-08T03:13:13.066Z",
  "leadId": "cl:rss:google-ai:b6aec8c05cfc3e2f",
  "lead": {
    "id": "cl:rss:google-ai:b6aec8c05cfc3e2f",
    "kind": "lead",
    "title": "Introducing Playground: Create and play custom games",
    "take": "2 SRC · sig 124 · pick 2026-10-08",
    "why": "LEAD_TODAY · picked · frozen at daily pick",
    "move": "Digest/Voice follow Brief lead · cycle label 003",
    "url": "https://blog.google/innovation-and-ai/technology/ai/playground-experimental-gaming-platform/",
    "sources": 2,
    "sig": 124
  },
  "rows": [
    {
      "id": "cl:rss:mistral:1ef243007176e85c",
      "kind": "companion",
      "title": "Introducing Mistral Large 4",
      "take": "9 SRC · sig 1999",
      "why": "Top corroborated Wire cluster · same pack as lead pick",
      "move": "Digest row · never displaces Brief lead",
      "url": "https://mistral.ai/news/mistral-large-4/",
      "sources": 9,
      "sig": 1999
    },
    {
      "id": "cl:hn:49980866",
      "kind": "rest",
      "title": "Google Nano Banana 2.1",
      "take": "4 SRC · sig 7",
      "why": "Top corroborated Wire cluster · same pack as lead pick",
      "move": "Digest row · never displaces Brief lead",
      "url": "https://gemini.google/overview/image-generation/",
      "sources": 4,
      "sig": 7
    },
    {
      "id": "cl:rss:openai:a097ef0d441a7216",
      "kind": "rest",
      "title": "GPT-6 and Intelligent UI for everyone",
      "take": "2 SRC · sig 524",
      "why": "Top corroborated Wire cluster · same pack as lead pick",
      "move": "Digest row · never displaces Brief lead",
      "url": "https://openai.com/index/gpt-6-for-everyone",
      "sources": 2,
      "sig": 524
    }
  ]
} as const;
