/** Pass A Digest/Voice unlock — frozen at daily lead pick (or first WROTE after it).
 * Generated by scripts/rank-snapshot.ts / digest tick. Do not edit by hand.
 * Cycle label stays 003. Mid-window crawls must not rewrite this file.
 */
import type { DigestUnlockSnapshot } from "@/lib/digest-unlock";

export const DIGEST_UNLOCK: DigestUnlockSnapshot = {
  "schema": 1,
  "cycleId": "003",
  "pickDate": "2026-10-10",
  "frozenAt": "2026-10-10T15:14:16.526Z",
  "leadId": "cl:hn:50030776",
  "lead": {
    "id": "cl:hn:50030776",
    "kind": "lead",
    "title": "The hazy OpenAI growth metric driving Wall Street",
    "take": "2 SRC · sig 4 · pick 2026-10-10",
    "why": "LEAD_TODAY · picked · frozen at daily pick",
    "move": "Digest/Voice follow Brief lead · cycle label 003",
    "url": "https://www.ft.com/content/62653892-2333-4953-a8d5-cfd760ae3257",
    "sources": 2,
    "sig": 4
  },
  "rows": [
    {
      "id": "cl:hn:50008187",
      "kind": "companion",
      "title": "OpenAI annualised revenues $20B less than previously signalled",
      "take": "6 SRC · sig 425",
      "why": "Top corroborated Wire cluster · same pack as lead pick",
      "move": "Digest row · never displaces Brief lead",
      "url": "https://www.cnbc.com/2026/10/08/open-ai-revenue-nvidia-oracle-coreweave.html",
      "sources": 6,
      "sig": 425
    },
    {
      "id": "cl:hn:50013972",
      "kind": "rest",
      "title": "OpenAI Safety Researchers Fired",
      "take": "4 SRC · sig 5",
      "why": "Top corroborated Wire cluster · same pack as lead pick",
      "move": "Digest row · never displaces Brief lead",
      "url": "https://twitter.com/balesni/status/2108262814003687745",
      "sources": 4,
      "sig": 5
    },
    {
      "id": "cl:hn:50023260",
      "kind": "rest",
      "title": "'Breathtaking,' 'Devastating': Mathematics Reels After New OpenAI Release",
      "take": "2 SRC · sig 25",
      "why": "Top corroborated Wire cluster · same pack as lead pick",
      "move": "Digest row · never displaces Brief lead",
      "url": "https://www.nytimes.com/2026/10/08/science/mathematicians-respond-openai-release.html",
      "sources": 2,
      "sig": 25
    },
    {
      "id": "cl:rss:huggingface:88e871d5a8d26738",
      "kind": "rest",
      "title": "Multimodal open d1 decision models for the edge",
      "take": "2 SRC · sig 1",
      "why": "Top corroborated Wire cluster · same pack as lead pick",
      "move": "Digest row · never displaces Brief lead",
      "url": "https://huggingface.co/blog/LiquidAI/open-d1",
      "sources": 2,
      "sig": 1
    }
  ]
} as const;
