/** Pass A Digest/Voice unlock — frozen at daily lead pick (or first WROTE after it).
 * Generated by scripts/rank-snapshot.ts / digest tick. Do not edit by hand.
 * Cycle label stays 003. Mid-window crawls must not rewrite this file.
 */
import type { DigestUnlockSnapshot } from "@/lib/digest-unlock";

export const DIGEST_UNLOCK: DigestUnlockSnapshot = {
  "schema": 1,
  "cycleId": "003",
  "pickDate": "2026-10-09",
  "frozenAt": "2026-10-09T11:28:17.635Z",
  "leadId": "cl:hn:50006368",
  "lead": {
    "id": "cl:hn:50006368",
    "kind": "lead",
    "title": "Google is launching a one-stop Gemini agent for your work tasks",
    "take": "2 SRC · sig 3 · pick 2026-10-09",
    "why": "LEAD_TODAY · picked · frozen at daily pick",
    "move": "Digest/Voice follow Brief lead · cycle label 003",
    "url": "https://www.theverge.com/tech/1007904/google-gemini-ai-agent-enterprise",
    "sources": 2,
    "sig": 3
  },
  "rows": [
    {
      "id": "cl:rss:openai:a097ef0d441a7216",
      "kind": "companion",
      "title": "GPT-6 and Intelligent UI for everyone",
      "take": "2 SRC · sig 749",
      "why": "Top corroborated Wire cluster · same pack as lead pick",
      "move": "Digest row · never displaces Brief lead",
      "url": "https://openai.com/index/gpt-6-for-everyone",
      "sources": 2,
      "sig": 749
    },
    {
      "id": "cl:rss:google-ai:b6aec8c05cfc3e2f",
      "kind": "rest",
      "title": "Introducing Playground: Create and play custom games",
      "take": "2 SRC · sig 160",
      "why": "Top corroborated Wire cluster · same pack as lead pick",
      "move": "Digest row · never displaces Brief lead",
      "url": "https://blog.google/innovation-and-ai/technology/ai/playground-experimental-gaming-platform/",
      "sources": 2,
      "sig": 160
    }
  ]
} as const;
