/** Beat 7 daily Brief lead — generated by scripts/rank-snapshot.ts from artifacts/sage/lead-history.json. Picked by the first crawl starting at/after 06:00 Istanbul on a date with no pick (catch-up), or LEAD_PICK_FORCE=1. */
import type { LeadEntry } from "@/lib/lead-pick";

export const LEAD_TODAY: LeadEntry | null = {
  "date": "2026-09-30",
  "at": "2026-09-30T03:16:33.351Z",
  "crawl_at": "2026-09-30T03:13:10Z",
  "excluded": [
    {
      "cluster_id": "cl:hn:49901481",
      "headline": "Trump and major AI executives sign \"morally binding\" voluntary controls",
      "reason": "politics:trump"
    },
    {
      "cluster_id": "cl:gnews:fc5935478d4b447b",
      "headline": "Morocco, Mistral AI release first open-source AI tools under AI made in Morocco roadmap",
      "reason": "GNW_ONLY"
    },
    {
      "cluster_id": "cl:rss:openai:dec620cb7225d243",
      "headline": "Introducing dots",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49881899",
      "headline": "Nvidia launches platform to quarantine rogue AI agents in 'milliseconds'",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49886005",
      "headline": "Anthropic's IPO prospectus shows AI vision, surging costs",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:rss:huggingface:09d1d26fa19dd694",
      "headline": "Holo4: powering generalist computer-use agents",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:rss:nvidia-dev:b2492ef6a6d58b24",
      "headline": "NVIDIA Open Agent Safety Platform: A Reference for Continuous In-Silicon Agent Monitoring",
      "reason": "age>=24h"
    }
  ],
  "cluster_id": "cl:hn:49891721",
  "headline": "Mistral CEO says U.S. AI safety debate masks competitors' 'negligence'",
  "url": "https://www.cnbc.com/2026/09/29/mistral-ai-safety-openai-anthropic.html",
  "sources": 8,
  "sig": 44,
  "reason": "picked",
  "first_at": "2026-09-29T08:20:04.000Z"
};

export const LEAD_YESTERDAY: LeadEntry | null = {
  "date": "2026-09-29",
  "at": "2026-09-29T03:21:05.067Z",
  "crawl_at": "2026-09-29T03:20:19Z",
  "excluded": [
    {
      "cluster_id": "cl:rss:nvidia-dev:b2492ef6a6d58b24",
      "headline": "NVIDIA Open Agent Safety Platform: A Reference for Continuous In-Silicon Agent Monitoring",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49870423",
      "headline": "Anthropic CEO Amodei set to meet with Trump",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49872468",
      "headline": "OpenAI pauses training of latest models after agents probed US Government sites",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:gnews:7e6aefa3a9071531",
      "headline": "Gemini Tarot Horoscope Today, September 29, 2026: Close people will be helpful, progress by coordinating with everyone",
      "reason": "GNW_ONLY"
    },
    {
      "cluster_id": "cl:hn:49870911",
      "headline": "Did Anthropic's A.I. Really Make a Scientific Discovery on Its Own?",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49870695",
      "headline": "Anthropic is a supply chain risk for all of us",
      "reason": "age>=24h"
    }
  ],
  "cluster_id": "cl:hn:49886416",
  "headline": "OpenAI Says It Will Not Release Newest A.I. Model Over Safety Concerns",
  "url": "https://www.nytimes.com/2026/09/28/technology/openai-astra-safety.html",
  "sources": 11,
  "sig": 43,
  "reason": "picked",
  "first_at": "2026-09-28T22:07:59.000Z"
};

export const LEAD_HELD = false;

/** Earliest member item of the lead story (null = unknown). Brief shows HELD once this is ≥24h old. */
export const LEAD_FIRST_AT: string | null = "2026-09-29T08:20:04.000Z";
