/** Beat 7 daily Brief lead — generated by scripts/rank-snapshot.ts from artifacts/sage/lead-history.json. Picked by the first crawl starting at/after 06:00 Istanbul on a date with no pick (catch-up), or LEAD_PICK_FORCE=1. */
import type { LeadEntry } from "@/lib/lead-pick";

export const LEAD_TODAY: LeadEntry | null = {
  "date": "2026-09-28",
  "at": "2026-09-28T03:23:38.381Z",
  "crawl_at": "2026-09-28T03:21:34Z",
  "excluded": [
    {
      "cluster_id": "cl:hn:49856913",
      "headline": "Unsecured OpenAI agents posted 53 user images on the internet",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49860545",
      "headline": "OpenAI pauses training of its 'most capable models'",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49864535",
      "headline": "OpenAI is pausing training for a second time",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49860279",
      "headline": "An OpenAI agent escaped its sandbox by hiding questions in DNS lookups",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49861517",
      "headline": "Top AI companies probing security incidents",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49862299",
      "headline": "OpenAI agents tried to bruteforce a UN website's API fields",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49856677",
      "headline": "Oxford University lets OpenAI train its AI models on Bodleian Library",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49855278",
      "headline": "OpenAI Says Its Models Engaged with US Government Websites in New Disclosure",
      "reason": "age>=24h"
    }
  ],
  "cluster_id": "cl:hn:49869486",
  "headline": "Anthropic/OpenAI sound alarm on AI safety and seek to shape how to control it",
  "url": "https://apnews.com/article/ai-slowdown-midterms-anthropic-openai-ipo-9a057de94eb8f30a2fdb5b938918627e",
  "sources": 4,
  "sig": 7,
  "reason": "picked",
  "first_at": "2026-09-27T12:12:34.000Z"
};

export const LEAD_YESTERDAY: LeadEntry | null = {
  "date": "2026-09-27",
  "at": "2026-09-27T03:21:22.037Z",
  "crawl_at": "2026-09-27T03:19:45Z",
  "excluded": [
    {
      "cluster_id": "cl:hn:49856913",
      "headline": "Unsecured OpenAI agents posted 53 user images on the internet",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49858360",
      "headline": "OpenAI's Rogue A.I. Agents Tried to Trick a Robot Detector",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49856665",
      "headline": "OpenAI bots meddled with multiple US Government agency sites",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:49851355",
      "headline": "OpenAI’s Systems Went Rogue and Meddled With U.S. Government Websites",
      "reason": "age>=24h"
    }
  ],
  "cluster_id": "cl:hn:49851154",
  "headline": "OpenAI investigating 'dozens' of instances of agents acting improperly",
  "url": "https://www.bbc.co.uk/news/articles/cw62jje658dlo",
  "sources": 2,
  "sig": 4,
  "first_at": "2026-09-25T23:02:54.000Z",
  "reason": "held",
  "note": "no qualifying story",
  "attempts": [
    {
      "at": "2026-09-27T03:21:22.037Z",
      "crawl_at": "2026-09-27T03:19:45Z",
      "excluded": [
        {
          "cluster_id": "cl:hn:49853688",
          "headline": "OpenAI says agents leaked 53 images from ChatGPT users",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49858360",
          "headline": "OpenAI's Rogue A.I. Agents Tried to Trick a Robot Detector",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49853692",
          "headline": "One company is at the center of a wave of rogue AI attacks",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49851355",
          "headline": "OpenAI’s Systems Went Rogue and Meddled With U.S. Government Websites",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49849985",
          "headline": "Revealing the details of how OpenAI agents hacked Hugging Face",
          "reason": "age>=24h"
        }
      ]
    },
    {
      "at": "2026-09-27T07:14:40.596Z",
      "crawl_at": "2026-09-27T07:14:27Z",
      "excluded": [
        {
          "cluster_id": "cl:hn:49853688",
          "headline": "OpenAI says agents leaked 53 images from ChatGPT users",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49858360",
          "headline": "OpenAI's Rogue A.I. Agents Tried to Trick a Robot Detector",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49853692",
          "headline": "One company is at the center of a wave of rogue AI attacks",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49851355",
          "headline": "OpenAI’s Systems Went Rogue and Meddled With U.S. Government Websites",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49849985",
          "headline": "Revealing the details of how OpenAI agents hacked Hugging Face",
          "reason": "age>=24h"
        }
      ]
    },
    {
      "at": "2026-09-27T11:20:57.412Z",
      "crawl_at": "2026-09-27T11:19:55Z",
      "excluded": [
        {
          "cluster_id": "cl:hn:49856913",
          "headline": "Unsecured OpenAI agents posted 53 user images on the internet",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49858360",
          "headline": "OpenAI's Rogue A.I. Agents Tried to Trick a Robot Detector",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49853692",
          "headline": "One company is at the center of a wave of rogue AI attacks",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49849985",
          "headline": "Revealing the details of how OpenAI agents hacked Hugging Face",
          "reason": "age>=24h"
        }
      ]
    },
    {
      "at": "2026-09-27T15:21:44.090Z",
      "crawl_at": "2026-09-27T15:21:10Z",
      "excluded": [
        {
          "cluster_id": "cl:hn:49856913",
          "headline": "Unsecured OpenAI agents posted 53 user images on the internet",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49858360",
          "headline": "OpenAI's Rogue A.I. Agents Tried to Trick a Robot Detector",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49853692",
          "headline": "One company is at the center of a wave of rogue AI attacks",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49849985",
          "headline": "Revealing the details of how OpenAI agents hacked Hugging Face",
          "reason": "age>=24h"
        }
      ]
    },
    {
      "at": "2026-09-27T19:27:14.437Z",
      "crawl_at": "2026-09-27T19:20:38Z",
      "excluded": [
        {
          "cluster_id": "cl:hn:49856913",
          "headline": "Unsecured OpenAI agents posted 53 user images on the internet",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49858360",
          "headline": "OpenAI's Rogue A.I. Agents Tried to Trick a Robot Detector",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49856665",
          "headline": "OpenAI bots meddled with multiple US Government agency sites",
          "reason": "age>=24h"
        },
        {
          "cluster_id": "cl:hn:49851355",
          "headline": "OpenAI’s Systems Went Rogue and Meddled With U.S. Government Websites",
          "reason": "age>=24h"
        }
      ]
    }
  ]
};

export const LEAD_HELD = false;

/** Earliest member item of the lead story (null = unknown). Brief shows HELD once this is ≥24h old. */
export const LEAD_FIRST_AT: string | null = "2026-09-27T12:12:34.000Z";
