/** Beat 7 daily Brief lead — generated by scripts/rank-snapshot.ts from artifacts/sage/lead-history.json. Picked by the first crawl starting at/after 06:00 Istanbul on a date with no pick (catch-up), or LEAD_PICK_FORCE=1. */
import type { LeadEntry } from "@/lib/lead-pick";

export const LEAD_TODAY: LeadEntry | null = {
  "date": "2026-10-10",
  "at": "2026-10-10T15:14:16.526Z",
  "crawl_at": "2026-10-10T15:14:07Z",
  "catch_up": true,
  "excluded": [
    {
      "cluster_id": "cl:hn:50008187",
      "headline": "OpenAI annualised revenues $20B less than previously signalled",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:50013972",
      "headline": "OpenAI Safety Researchers Fired",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:gnews:24c8282971995657",
      "headline": "Google's Gemini 4 \"Carbon\" model is reportedly matching Anthropic's Opus 5.5 coding performance",
      "reason": "GNW_ONLY"
    },
    {
      "cluster_id": "cl:hn:50023260",
      "headline": "'Breathtaking,' 'Devastating': Mathematics Reels After New OpenAI Release",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:rss:huggingface:88e871d5a8d26738",
      "headline": "Multimodal open d1 decision models for the edge",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:rss:huggingface:16b7810afb00bdc0",
      "headline": "Introducing Falcon ASR",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:hn:50009239",
      "headline": "USA Today sues OpenAI for copyright infringement over AI training",
      "reason": "age>=24h"
    }
  ],
  "cluster_id": "cl:hn:50030776",
  "headline": "The hazy OpenAI growth metric driving Wall Street",
  "url": "https://www.ft.com/content/62653892-2333-4953-a8d5-cfd760ae3257",
  "sources": 2,
  "sig": 4,
  "reason": "picked",
  "first_at": "2026-10-09T20:57:10.000Z"
};

export const LEAD_YESTERDAY: LeadEntry | null = {
  "date": "2026-10-09",
  "at": "2026-10-09T11:28:17.635Z",
  "crawl_at": "2026-10-09T11:27:50Z",
  "catch_up": true,
  "excluded": [
    {
      "cluster_id": "cl:rss:mistral:1ef243007176e85c",
      "headline": "Introducing Mistral Large 4",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:rss:openai:a097ef0d441a7216",
      "headline": "GPT-6 and Intelligent UI for everyone",
      "reason": "age>=24h"
    },
    {
      "cluster_id": "cl:rss:google-ai:b6aec8c05cfc3e2f",
      "headline": "Introducing Playground: Create and play custom games",
      "reason": "age>=24h"
    }
  ],
  "cluster_id": "cl:hn:50006368",
  "headline": "Google is launching a one-stop Gemini agent for your work tasks",
  "url": "https://www.theverge.com/tech/1007904/google-gemini-ai-agent-enterprise",
  "sources": 2,
  "sig": 3,
  "reason": "picked",
  "first_at": "2026-10-08T14:39:57.000Z"
};

export const LEAD_HELD = false;

/** Earliest member item of the lead story (null = unknown). Brief shows HELD once this is ≥24h old. */
export const LEAD_FIRST_AT: string | null = "2026-10-09T20:57:10.000Z";
