/** Source health ledger snapshot (Beat 2) — generated by bun run ingest from artifacts/sage/source-health.json. Rail/UI only; never Brief. */
import type { SourceHealthRow } from "@/lib/source-health";

export const SOURCE_HEALTH_AT = "2026-09-27T23:19:29Z";

export const SOURCE_HEALTH: SourceHealthRow[] = [
  {"id":"arxiv","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-27T23:19:29Z","last_fail":null,"fail_reason":null,"streak_ok":32,"streak_fail":0,"items_last":11,"runs_7d":32,"ok_7d":32},
  {"id":"crossref","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-27T23:19:29Z","last_fail":null,"fail_reason":null,"streak_ok":32,"streak_fail":0,"items_last":1,"runs_7d":32,"ok_7d":32},
  {"id":"github","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-27T23:19:29Z","last_fail":null,"fail_reason":null,"streak_ok":32,"streak_fail":0,"items_last":2,"runs_7d":32,"ok_7d":32},
  {"id":"gnews","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-27T23:19:29Z","last_fail":null,"fail_reason":null,"streak_ok":32,"streak_fail":0,"items_last":32,"runs_7d":32,"ok_7d":32},
  {"id":"hf","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-27T23:19:29Z","last_fail":null,"fail_reason":null,"streak_ok":32,"streak_fail":0,"items_last":50,"runs_7d":32,"ok_7d":32},
  {"id":"hn","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-27T23:19:29Z","last_fail":null,"fail_reason":null,"streak_ok":32,"streak_fail":0,"items_last":47,"runs_7d":32,"ok_7d":32},
  {"id":"openalex","state":"flaky","status":"ok","paused_until":null,"last_ok":"2026-09-27T23:19:29Z","last_fail":"2026-09-26T03:20:25Z","fail_reason":"HTTP 429","streak_ok":6,"streak_fail":0,"items_last":3,"runs_7d":24,"ok_7d":6},
  {"id":"rss_labs","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-27T23:19:29Z","last_fail":null,"fail_reason":null,"streak_ok":32,"streak_fail":0,"items_last":104,"runs_7d":32,"ok_7d":32},
  {"id":"rss_security","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-27T23:19:29Z","last_fail":null,"fail_reason":null,"streak_ok":32,"streak_fail":0,"items_last":27,"runs_7d":32,"ok_7d":32},
  {"id":"wikidata","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-27T23:19:29Z","last_fail":null,"fail_reason":null,"streak_ok":32,"streak_fail":0,"items_last":3,"runs_7d":32,"ok_7d":32},
];
