/** Source health ledger snapshot (Beat 2) — generated by bun run ingest from artifacts/sage/source-health.json. Rail/UI only; never Brief. */
import type { SourceHealthRow } from "@/lib/source-health";

export const SOURCE_HEALTH_AT = "2026-10-09T11:27:50Z";

export const SOURCE_HEALTH: SourceHealthRow[] = [
  {"id":"arxiv","state":"flaky","status":"ok","paused_until":null,"last_ok":"2026-10-09T11:27:50Z","last_fail":"2026-10-06T07:15:31Z","fail_reason":"timeout after 20000ms budget · last good: 9 cached enrich + 5 kept shelf","streak_ok":10,"streak_fail":0,"items_last":29,"runs_7d":33,"ok_7d":28},
  {"id":"crossref","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-10-09T11:27:50Z","last_fail":null,"fail_reason":null,"streak_ok":94,"streak_fail":0,"items_last":1,"runs_7d":33,"ok_7d":33},
  {"id":"github","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-10-09T11:27:50Z","last_fail":null,"fail_reason":null,"streak_ok":94,"streak_fail":0,"items_last":2,"runs_7d":33,"ok_7d":33},
  {"id":"gnews","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-10-09T11:27:50Z","last_fail":null,"fail_reason":null,"streak_ok":94,"streak_fail":0,"items_last":29,"runs_7d":33,"ok_7d":33},
  {"id":"hf","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-10-09T11:27:50Z","last_fail":null,"fail_reason":null,"streak_ok":94,"streak_fail":0,"items_last":50,"runs_7d":33,"ok_7d":33},
  {"id":"hn","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-10-09T11:27:50Z","last_fail":null,"fail_reason":null,"streak_ok":94,"streak_fail":0,"items_last":66,"runs_7d":33,"ok_7d":33},
  {"id":"openalex","state":"flaky","status":"ok","paused_until":null,"last_ok":"2026-10-09T11:27:50Z","last_fail":"2026-10-06T03:20:50Z","fail_reason":"HTTP 429","streak_ok":6,"streak_fail":0,"items_last":5,"runs_7d":10,"ok_7d":6},
  {"id":"rss_labs","state":"flaky","status":"ok","paused_until":null,"last_ok":"2026-10-09T11:27:50Z","last_fail":"2026-10-04T03:14:31Z","fail_reason":"timeout after 30000ms budget","streak_ok":23,"streak_fail":0,"items_last":104,"runs_7d":33,"ok_7d":32},
  {"id":"rss_security","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-10-09T11:27:50Z","last_fail":null,"fail_reason":null,"streak_ok":94,"streak_fail":0,"items_last":28,"runs_7d":33,"ok_7d":33},
  {"id":"wikidata","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-10-09T11:27:50Z","last_fail":null,"fail_reason":null,"streak_ok":94,"streak_fail":0,"items_last":3,"runs_7d":33,"ok_7d":33},
];
