/** Source health ledger snapshot (Beat 2) — generated by bun run ingest from artifacts/sage/source-health.json. Rail/UI only; never Brief. */
import type { SourceHealthRow } from "@/lib/source-health";

export const SOURCE_HEALTH_AT = "2026-09-30T07:21:22Z";

export const SOURCE_HEALTH: SourceHealthRow[] = [
  {"id":"arxiv","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-30T07:21:22Z","last_fail":null,"fail_reason":null,"streak_ok":47,"streak_fail":0,"items_last":29,"runs_7d":47,"ok_7d":47},
  {"id":"crossref","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-30T07:21:22Z","last_fail":null,"fail_reason":null,"streak_ok":47,"streak_fail":0,"items_last":1,"runs_7d":47,"ok_7d":47},
  {"id":"github","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-30T07:21:22Z","last_fail":null,"fail_reason":null,"streak_ok":47,"streak_fail":0,"items_last":3,"runs_7d":47,"ok_7d":47},
  {"id":"gnews","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-30T07:21:22Z","last_fail":null,"fail_reason":null,"streak_ok":47,"streak_fail":0,"items_last":42,"runs_7d":47,"ok_7d":47},
  {"id":"hf","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-30T07:21:22Z","last_fail":null,"fail_reason":null,"streak_ok":47,"streak_fail":0,"items_last":50,"runs_7d":47,"ok_7d":47},
  {"id":"hn","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-30T07:21:22Z","last_fail":null,"fail_reason":null,"streak_ok":47,"streak_fail":0,"items_last":65,"runs_7d":47,"ok_7d":47},
  {"id":"openalex","state":"fail","status":"paused","paused_until":"2026-09-30T07:21:35Z","last_ok":"2026-09-29T23:20:31Z","last_fail":"2026-09-30T07:21:22Z","fail_reason":"HTTP 429","streak_ok":0,"streak_fail":2,"items_last":0,"runs_7d":39,"ok_7d":19},
  {"id":"rss_labs","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-30T07:21:22Z","last_fail":null,"fail_reason":null,"streak_ok":47,"streak_fail":0,"items_last":104,"runs_7d":47,"ok_7d":47},
  {"id":"rss_security","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-30T07:21:22Z","last_fail":null,"fail_reason":null,"streak_ok":47,"streak_fail":0,"items_last":27,"runs_7d":47,"ok_7d":47},
  {"id":"wikidata","state":"ok","status":"ok","paused_until":null,"last_ok":"2026-09-30T07:21:22Z","last_fail":null,"fail_reason":null,"streak_ok":47,"streak_fail":0,"items_last":3,"runs_7d":47,"ok_7d":47},
];
