/** Beat 10 topic heat — generated by scripts/rank-snapshot.ts (npm postingest). One value per 4h routine window (last crawl in the window); null = gap. */
import type { HeatWindow } from "@/lib/topic-heat";

export const TOPIC_HEAT_AT = "2026-10-09T11:27:50Z";
export const TOPIC_HEAT_CRAWLS = 84;
export const TOPIC_HEAT_WINDOWS: HeatWindow[] = [
  {
    "start": 1791471600000,
    "label": "18",
    "crawl_at": null,
    "counts": null,
    "labs": null
  },
  {
    "start": 1791486000000,
    "label": "22",
    "crawl_at": null,
    "counts": null,
    "labs": null
  },
  {
    "start": 1791500400000,
    "label": "02",
    "crawl_at": null,
    "counts": null,
    "labs": null
  },
  {
    "start": 1791514800000,
    "label": "06",
    "crawl_at": null,
    "counts": null,
    "labs": null
  },
  {
    "start": 1791529200000,
    "label": "10",
    "crawl_at": null,
    "counts": null,
    "labs": null
  },
  {
    "start": 1791543600000,
    "label": "14",
    "crawl_at": "2026-10-09T11:27:50Z",
    "counts": {
      "anthropic": 27,
      "openai": 40,
      "google": 45,
      "nvidia": 23,
      "hf": 14,
      "other": 15
    },
    "labs": {
      "mistral": 14,
      "meta": 1
    }
  }
];
