/** Beat 10 topic heat — generated by scripts/rank-snapshot.ts (npm postingest). One value per 4h routine window (last crawl in the window); null = gap. */
import type { HeatWindow } from "@/lib/topic-heat";

export const TOPIC_HEAT_AT = "2026-09-28T15:34:12Z";
export const TOPIC_HEAT_CRAWLS = 28;
export const TOPIC_HEAT_WINDOWS: HeatWindow[] = [
  {
    "start": 1790535600000,
    "label": "22",
    "crawl_at": "2026-09-27T19:20:38Z",
    "counts": {
      "anthropic": 20,
      "openai": 45,
      "google": 43,
      "nvidia": 23,
      "hf": 13,
      "other": 15
    },
    "labs": {
      "meta": 1,
      "xiaomi": 1,
      "mistral": 13
    }
  },
  {
    "start": 1790550000000,
    "label": "02",
    "crawl_at": "2026-09-27T23:19:29Z",
    "counts": {
      "anthropic": 19,
      "openai": 42,
      "google": 43,
      "nvidia": 24,
      "hf": 12,
      "other": 15
    },
    "labs": {
      "meta": 1,
      "xiaomi": 1,
      "mistral": 13
    }
  },
  {
    "start": 1790564400000,
    "label": "06",
    "crawl_at": "2026-09-28T03:21:34Z",
    "counts": {
      "anthropic": 19,
      "openai": 48,
      "google": 42,
      "nvidia": 24,
      "hf": 15,
      "other": 14
    },
    "labs": {
      "xiaomi": 1,
      "mistral": 13
    }
  },
  {
    "start": 1790578800000,
    "label": "10",
    "crawl_at": "2026-09-28T07:23:25Z",
    "counts": {
      "anthropic": 20,
      "openai": 47,
      "google": 42,
      "nvidia": 25,
      "hf": 15,
      "other": 14
    },
    "labs": {
      "xiaomi": 1,
      "mistral": 13
    }
  },
  {
    "start": 1790593200000,
    "label": "14",
    "crawl_at": "2026-09-28T11:19:15Z",
    "counts": {
      "anthropic": 19,
      "openai": 41,
      "google": 46,
      "nvidia": 30,
      "hf": 15,
      "other": 14
    },
    "labs": {
      "xiaomi": 1,
      "mistral": 13
    }
  },
  {
    "start": 1790607600000,
    "label": "18",
    "crawl_at": "2026-09-28T15:34:12Z",
    "counts": {
      "anthropic": 19,
      "openai": 39,
      "google": 47,
      "nvidia": 27,
      "hf": 15,
      "other": 13
    },
    "labs": {
      "xiaomi": 1,
      "mistral": 12
    }
  }
];
