/** Beat 10 topic heat — generated by scripts/rank-snapshot.ts (npm postingest). One value per 4h routine window (last crawl in the window); null = gap. */
import type { HeatWindow } from "@/lib/topic-heat";

export const TOPIC_HEAT_AT = "2026-10-03T23:20:49Z";
export const TOPIC_HEAT_CRAWLS = 60;
export const TOPIC_HEAT_WINDOWS: HeatWindow[] = [
  {
    "start": 1790996400000,
    "label": "06",
    "crawl_at": "2026-10-03T03:17:23Z",
    "counts": {
      "anthropic": 10,
      "openai": 37,
      "google": 49,
      "nvidia": 26,
      "hf": 15,
      "other": 16
    },
    "labs": {
      "xai": 1,
      "meta": 4,
      "mistral": 12
    }
  },
  {
    "start": 1791010800000,
    "label": "10",
    "crawl_at": "2026-10-03T07:12:59Z",
    "counts": {
      "anthropic": 11,
      "openai": 37,
      "google": 47,
      "nvidia": 26,
      "hf": 15,
      "other": 16
    },
    "labs": {
      "meta": 4,
      "xai": 1,
      "mistral": 12
    }
  },
  {
    "start": 1791025200000,
    "label": "14",
    "crawl_at": "2026-10-03T11:16:29Z",
    "counts": {
      "anthropic": 14,
      "openai": 31,
      "google": 48,
      "nvidia": 25,
      "hf": 14,
      "other": 15
    },
    "labs": {
      "meta": 3,
      "xai": 1,
      "mistral": 12
    }
  },
  {
    "start": 1791039600000,
    "label": "18",
    "crawl_at": "2026-10-03T15:20:35Z",
    "counts": {
      "anthropic": 11,
      "openai": 32,
      "google": 49,
      "nvidia": 25,
      "hf": 14,
      "other": 15
    },
    "labs": {
      "meta": 3,
      "xai": 1,
      "mistral": 12
    }
  },
  {
    "start": 1791054000000,
    "label": "22",
    "crawl_at": "2026-10-03T19:11:33Z",
    "counts": {
      "anthropic": 11,
      "openai": 30,
      "google": 49,
      "nvidia": 25,
      "hf": 15,
      "other": 15
    },
    "labs": {
      "meta": 3,
      "xai": 1,
      "mistral": 12
    }
  },
  {
    "start": 1791068400000,
    "label": "02",
    "crawl_at": "2026-10-03T23:20:49Z",
    "counts": {
      "anthropic": 12,
      "openai": 27,
      "google": 49,
      "nvidia": 24,
      "hf": 15,
      "other": 14
    },
    "labs": {
      "meta": 2,
      "mistral": 12
    }
  }
];
