/** Beat 7 Brief Wire — generated by scripts/rank-snapshot.ts (npm postingest). Multi-source, AI-filtered clusters; never Taste; never displaces the lead. */
import type { WireRow } from "@/lib/wire";

export const WIRE_CRAWL_AT = "2026-10-03T15:20:35Z";
export const WIRE_PREV_CRAWL_AT: string | null = "2026-10-03T11:16:29Z";
export const WIRE_NEW = 1;
export const WIRE_MOVED = 1;

export const WIRE_ROWS: WireRow[] = [
  {
    "id": "cl:hn:49938646",
    "title": "The Sleuths Who Expose When AI Goes Rogue",
    "url": "https://www.wsj.com/tech/ai/swarm-chaser-openai-rubygems-hugging-face-7d55b51f",
    "at": "2026-10-02T21:11:18Z",
    "sources": 2,
    "score": 3,
    "member_ids": [
      "hn:49938646",
      "hn:49932295",
      "gnews:50b72429f34acc50"
    ],
    "is_new": false,
    "rank": 1,
    "prev_rank": null,
    "status": "new"
  },
  {
    "id": "cl:hn:49925606",
    "title": "US judge dismisses Chegg, Penske antitrust suits over Google AI Overviews",
    "url": "https://reuters.com/legal/litigation/google-wins-dismissal-chegg-penske-media-lawsuits-over-ai-overviews-2026-10-01",
    "at": "2026-10-01T20:11:55Z",
    "sources": 2,
    "score": 20,
    "member_ids": [
      "hn:49925606",
      "gnews:727fe17491b140b0"
    ],
    "is_new": false,
    "rank": 2,
    "prev_rank": 1,
    "status": "down"
  }
];
