/** Beat 7 Brief Wire — generated by scripts/rank-snapshot.ts (npm postingest). Multi-source, AI-filtered clusters; never Taste; never displaces the lead. */
import type { WireRow } from "@/lib/wire";

export const WIRE_CRAWL_AT = "2026-09-26T11:20:04Z";
export const WIRE_PREV_CRAWL_AT: string | null = "2026-09-26T07:20:20Z";
export const WIRE_NEW = 2;
export const WIRE_MOVED = 3;

export const WIRE_ROWS: WireRow[] = [
  {
    "id": "cl:hn:49853688",
    "title": "OpenAI says agents leaked 53 images from ChatGPT users",
    "url": "https://www.theguardian.com/technology/2026/sep/25/openai-agents-leaked-53-images-chatgpt",
    "at": "2026-09-26T06:07:54Z",
    "sources": 3,
    "score": 7,
    "member_ids": [
      "hn:49853688",
      "hn:49850868",
      "gnews:934323eb23d8c678",
      "gnews:bea8a0633249df78"
    ],
    "is_new": false,
    "rank": 1,
    "prev_rank": 3,
    "status": "up"
  },
  {
    "id": "cl:hn:49853401",
    "title": "OpenAI works to understand scope of agent activity as user data leak emerges",
    "url": "https://www.reuters.com/world/openai-works-understand-full-scope-agent-activity-user-data-leak-emerges-2026-09-25/",
    "at": "2026-09-26T05:10:45Z",
    "sources": 2,
    "score": 4,
    "member_ids": [
      "hn:49853401",
      "gnews:ce6f0076c57a4a15"
    ],
    "is_new": true,
    "rank": 2,
    "prev_rank": null,
    "status": "new"
  },
  {
    "id": "cl:hn:49851355",
    "title": "OpenAI’s Systems Went Rogue and Meddled With U.S. Government Websites",
    "url": "https://www.nytimes.com/2026/09/25/technology/openais-ai-us-government-websites.html",
    "at": "2026-09-25T23:22:18Z",
    "sources": 2,
    "score": 47,
    "member_ids": [
      "hn:49851355",
      "gnews:24f0e4b4a185642e"
    ],
    "is_new": false,
    "rank": 3,
    "prev_rank": null,
    "status": "new"
  },
  {
    "id": "cl:hn:49851120",
    "title": "How OpenAI's Rogue A.I. Agents Tried to Trick a Robot Detector",
    "url": "https://www.nytimes.com/2026/09/25/technology/openai-hugging-face-hack.html",
    "at": "2026-09-25T22:59:32Z",
    "sources": 2,
    "score": 5,
    "member_ids": [
      "hn:49851120",
      "gnews:0377d72788cc2933"
    ],
    "is_new": false,
    "rank": 4,
    "prev_rank": 2,
    "status": "down"
  },
  {
    "id": "cl:hn:49830606",
    "title": "Google’s Project Suncatcher to put ML infrastructure in space",
    "url": "https://blog.google/innovation-and-ai/models-and-research/google-research/google-project-suncatcher-facts/",
    "at": "2026-09-25T07:04:34Z",
    "sources": 2,
    "score": 227,
    "member_ids": [
      "hn:49830606",
      "gnews:8b01c17054630903"
    ],
    "is_new": false,
    "rank": 5,
    "prev_rank": 1,
    "status": "down"
  }
];
