/** Beat 7 Brief Wire — generated by scripts/rank-snapshot.ts (npm postingest). Multi-source, AI-filtered clusters; never Taste; never displaces the lead. */
import type { WireRow } from "@/lib/wire";

export const WIRE_CRAWL_AT = "2026-10-06T15:19:47Z";
export const WIRE_PREV_CRAWL_AT: string | null = "2026-10-06T11:19:46Z";
export const WIRE_NEW = 0;
export const WIRE_MOVED = 1;

export const WIRE_ROWS: WireRow[] = [
  {
    "id": "cl:hn:49975345",
    "title": "Anthropic Subscriptions Offer 5x+ More Value Than OpenAI",
    "url": "https://newsletter.semianalysis.com/p/anthropic-subscriptions-offer-5x",
    "at": "2026-10-06T07:29:50Z",
    "sources": 3,
    "score": 75,
    "member_ids": [
      "hn:49975345",
      "hn:49969927",
      "gnews:4418bd00871bc18b",
      "gnews:30bb873abd279e2d"
    ],
    "is_new": false,
    "rank": 1,
    "prev_rank": 1,
    "status": "same"
  },
  {
    "id": "cl:hn:49972816",
    "title": "Third conversation with Claude that Anthropic reported to police since August",
    "url": "https://www.tomshardware.com/tech-industry/artificial-intelligence/anthropic-reports-florida-womans-claude-diary-threat-to-shoot-up-sheriffs-office-felony-charge-follows-its-at-least-the-third-such-conversation-to-reach-police-since-august",
    "at": "2026-10-06T00:53:45Z",
    "sources": 2,
    "score": 3,
    "member_ids": [
      "hn:49972816",
      "gnews:4319eff64ea5228c"
    ],
    "is_new": false,
    "rank": 2,
    "prev_rank": 2,
    "status": "same"
  },
  {
    "id": "cl:hn:49961057",
    "title": "Anthropic reported diary entry to police, woman faces felony charge",
    "url": "https://www.techspot.com/news/114091-florida-woman-used-claude-diary-anthropic-reported-shoot.html",
    "at": "2026-10-05T21:16:03Z",
    "sources": 2,
    "score": 771,
    "member_ids": [
      "hn:49961057",
      "hn:49958089",
      "gnews:ecb3ae23ff88741d",
      "gnews:6821df2e7eec72df"
    ],
    "is_new": false,
    "rank": 3,
    "prev_rank": 3,
    "status": "same"
  },
  {
    "id": "cl:hn:49969929",
    "title": "Pentagon stops using Anthropic AI tools after blacklisting company, BBC told",
    "url": "https://www.bbc.co.uk/news/articles/c5j9x9pr0240o",
    "at": "2026-10-05T20:07:10Z",
    "sources": 2,
    "score": 12,
    "member_ids": [
      "hn:49969929",
      "gnews:415c71beb6847263"
    ],
    "is_new": false,
    "rank": 4,
    "prev_rank": 4,
    "status": "same"
  },
  {
    "id": "cl:hn:49955908",
    "title": "Powerful open model is set to shake up AI race",
    "url": "https://www.axios.com/2026/10/04/reflection-open-weight-ai",
    "at": "2026-10-04T17:28:16Z",
    "sources": 2,
    "score": 1,
    "member_ids": [
      "hn:49955908",
      "gnews:8e16c65bfd16491e"
    ],
    "is_new": false,
    "rank": 5,
    "prev_rank": 6,
    "status": "up"
  }
];
