#!/usr/bin/env bun
/**
 * B1 · build-time stamp for the static export. Runs in `prebuild` right after the hard gate and
 * writes src/data/build-stamp.ts (gitignored). The page imports it — no .next/BUILD_ID read, no
 * server boot time, no request-time filesystem. Repo-only (clean CI checkout OK).
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { checkCurrent } from "./lib/current-gate.mjs";
import { activePauses } from "../src/lib/source-pause.ts";

const deskRoot = resolve(import.meta.dirname ?? new URL(".", import.meta.url).pathname, "..");
const gate = checkCurrent({ deskRoot });
if (!gate.ok) {
  for (const e of gate.errors) console.error(`SAGE HARD GATE: ${e}`);
  process.exit(1);
}
function gitSha() {
  const env = process.env.CF_PAGES_COMMIT_SHA || process.env.GITHUB_SHA;
  if (env) return env;
  try {
    return execFileSync("git", ["rev-parse", "HEAD"], { cwd: deskRoot, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return "";
  }
}
const builtAt = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
const sha = gitSha();
const buildId = process.env.SAGE_BUILD_ID || `${sha ? sha.slice(0, 7) : "nogit"}-${builtAt.replace(/[-:TZ]/g, "").slice(0, 12)}`;
// Merge crawl pause state (committed, optional): only pauses still in force at build time.
const statePath = resolve(deskRoot, "artifacts/sage/source-state.json");
let sourceState = null;
if (existsSync(statePath)) {
  try {
    sourceState = JSON.parse(readFileSync(statePath, "utf8"));
  } catch {
    console.error("build-stamp: source-state.json unreadable — treating as no pauses");
  }
}
const pauses = activePauses(sourceState, Date.parse(builtAt));
const stamp = {
  buildId,
  builtAt,
  commit: sha,
  cycleId: gate.lock.id,
  compiledAt: gate.lock.compiled_at ?? "",
  crawledAt: gate.lock.crawled_at ?? "",
  pauses,
};
const out = resolve(deskRoot, "src/data/build-stamp.ts");
writeFileSync(
  out,
  `/** Generated by scripts/build-stamp.mjs (prebuild) — do not edit, not committed. */\nexport const BUILD_STAMP = ${JSON.stringify(stamp, null, 2)} as const;\n`,
);
console.log(
  `build-stamp OK — ${buildId} · cycle ${stamp.cycleId} · crawl ${stamp.crawledAt} · paused ${Object.entries(pauses).map(([id, p]) => `${id}→${p.until}`).join(", ") || "none"}`,
);
