#!/usr/bin/env bun
/**
 * OPT win 3 — write src/data/desk-view.ts, the ONE data module the desk client imports for crawl data.
 * Runs at the end of scripts/rank-snapshot.ts (npm postingest / rank:snapshot) in a fresh process, so it reads
 * the modules ingest + rank-snapshot just wrote. Deterministic: same raw modules ⇒ byte-identical output.
 *   bun scripts/desk-view.ts          write (only when the content changed)
 *   bun scripts/desk-view.ts --check  exit 1 if src/data/desk-view.ts is not what the raw modules produce
 * See src/lib/desk-view.ts for what is kept and why.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { CRAWL, CRAWL_AT } from "@/data/x-crawl";
import { GNEWS_RSS } from "@/data/gnews-rss";
import { HN_PULSE } from "@/data/hn-pulse";
import { RSS_LABS } from "@/data/rss-labs";
import { RSS_SECURITY } from "@/data/rss-security";
import { PULSE_CLUSTERS, PULSE_CLUSTERS_AT } from "@/data/pulse-clusters";
import { SOURCE_HEALTH, SOURCE_HEALTH_AT } from "@/data/source-health";
import { WIRE_CRAWL_AT, WIRE_PREV_CRAWL_AT, WIRE_ROWS } from "@/data/wire";
import { TOPIC_HEAT_AT, TOPIC_HEAT_WINDOWS } from "@/data/topic-heat";
import { RANK_CURRENT, RANK_MOVED, RANK_PREV } from "@/data/corroboration-rank";
import { LEAD_FIRST_AT, LEAD_HELD, LEAD_TODAY, LEAD_YESTERDAY } from "@/data/lead-pick";
import { SHELF } from "@/data/shelf";
import { PAPERS } from "@/data/papers";
import { memberInfo } from "@/lib/member-info";
import { buildDeskView, slimLead } from "@/lib/desk-view";
import type { PaperInput } from "@/lib/pulse-v5";

const desk = resolve(import.meta.dir, "..");
const outPath = resolve(desk, "src/data/desk-view.ts");

const j = (v: unknown) => JSON.stringify(v);
/** One array element / object entry per line: readable diffs, no pretty-print bloat. */
const lines = (arr: readonly unknown[]) => (arr.length ? `[\n${arr.map((v) => `  ${j(v)},`).join("\n")}\n]` : "[]");
const entries = (o: Record<string, unknown>) => {
  const e = Object.entries(o);
  return e.length ? `{\n${e.map(([k, v]) => `  ${j(k)}: ${j(v)},`).join("\n")}\n}` : "{}";
};
/** Rank snapshots minus `at` (the snapshot's wall-clock write time — never rendered; keeps reruns byte-identical). */
const noAt = <T extends { at?: unknown }>(s: T | null) => {
  if (!s) return null;
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { at, ...rest } = s;
  return rest;
};

const itemIds = [...HN_PULSE.map((h) => h.id), ...GNEWS_RSS.map((g) => g.id), ...RSS_LABS.map((r) => r.id), ...RSS_SECURITY.map((r) => r.id)];
const members = memberInfo();
// The client recovers the crawl-item list as "every member id not under x:" (crawlItemIds) — make sure that holds.
for (const id of itemIds) if (id.startsWith("x:")) throw new Error(`desk-view: crawl item id ${id} collides with the X namespace`);
if (JSON.stringify([...new Set(itemIds)]) !== JSON.stringify(Object.keys(members).filter((id) => !id.startsWith("x:"))))
  throw new Error("desk-view: memberInfo order ≠ crawl item order");
const view = buildDeskView({
  clusters: PULSE_CLUSTERS,
  members,
  gnews: GNEWS_RSS.map((g) => ({ id: g.id, title: g.title, publisher: g.publisher })),
  xPosts: CRAWL,
  papers: PAPERS as unknown as (PaperInput & Record<string, unknown>)[],
});

const body = `/**
 * Slim client view of crawl ${PULSE_CLUSTERS_AT} — GENERATED by scripts/desk-view.ts (run by rank-snapshot / npm postingest).
 * Do not edit. The desk imports crawl data ONLY from here; raw src/data modules stay for scripts and tests.
 * pages-coherence: DESK_VIEW_AT must equal CRAWL_AT (x-crawl) = PULSE_CLUSTERS_AT = WIRE_CRAWL_AT = TOPIC_HEAT_AT.
 */
import type { MovedRow, RankSnapshot } from "@/lib/corroboration";
import type { MemberRow, OrphanCluster, SlimLead, XPost } from "@/lib/desk-view";
import type { PaperInput } from "@/lib/pulse-v5";
import type { SourceHealthRow } from "@/lib/source-health";
import type { HeatWindow } from "@/lib/topic-heat";
import type { WireRow } from "@/lib/wire";

export const DESK_VIEW_AT = ${j(PULSE_CLUSTERS_AT)};
export const CRAWL_AT = ${j(CRAWL_AT)};
export const PULSE_CLUSTERS_AT = ${j(PULSE_CLUSTERS_AT)};
export const SOURCE_HEALTH_AT = ${j(SOURCE_HEALTH_AT)};
export const WIRE_CRAWL_AT = ${j(WIRE_CRAWL_AT)};
export const WIRE_PREV_CRAWL_AT: string | null = ${j(WIRE_PREV_CRAWL_AT)};
export const TOPIC_HEAT_AT = ${j(TOPIC_HEAT_AT)};

export const LEAD_HELD: boolean = ${j(LEAD_HELD)};
export const LEAD_FIRST_AT: string | null = ${j(LEAD_FIRST_AT)};
export const LEAD_TODAY: SlimLead | null = ${j(slimLead(LEAD_TODAY))};
export const LEAD_YESTERDAY: SlimLead | null = ${j(slimLead(LEAD_YESTERDAY))};

export const RANK_CURRENT: Omit<RankSnapshot, "at"> = ${j(noAt(RANK_CURRENT))};
export const RANK_PREV: Omit<RankSnapshot, "at"> | null = ${j(noAt(RANK_PREV))};
export const RANK_MOVED: MovedRow[] = ${lines(RANK_MOVED)};

export const WIRE_ROWS: WireRow[] = ${lines(WIRE_ROWS)};

export const TOPIC_HEAT_WINDOWS: HeatWindow[] = ${lines(TOPIC_HEAT_WINDOWS)};

export const SOURCE_HEALTH: SourceHealthRow[] = ${lines(SOURCE_HEALTH)};

/**
 * One record per crawl item + X post: b badge · p publisher · t title · a time · u url · s signal · m summary · sec ·
 * dt drawer title · c the Pulse cluster this item leads (cluster leads come first, in cluster order). See src/lib/desk-view.ts.
 */
export const MEMBER_ROWS: Record<string, MemberRow> = ${entries(view.memberRows)};

/** Clusters whose lead is not a crawl item (normally empty). */
export const ORPHAN_CLUSTERS: OrphanCluster[] = ${lines(view.orphanClusters)};

export const X_POSTS: XPost[] = ${lines(view.xPosts)};

export const PAPERS: PaperInput[] = ${lines(view.papers)};

export const SHELF: { href: string; label: string; reason: string }[] = ${lines(SHELF)};
`;

const check = process.argv.includes("--check");
const prev = existsSync(outPath) ? readFileSync(outPath, "utf8") : null;
if (check) {
  if (prev !== body) {
    console.error(`desk-view STALE — src/data/desk-view.ts ≠ raw modules (crawl ${PULSE_CLUSTERS_AT}); run bun scripts/desk-view.ts`);
    process.exit(1);
  }
  console.log(`desk-view OK (in sync) · crawl ${PULSE_CLUSTERS_AT}`);
} else {
  if (prev !== body) writeFileSync(outPath, body);
  console.log(
    `desk-view ${prev === body ? "unchanged" : "written"} · crawl ${PULSE_CLUSTERS_AT} · ${Object.keys(view.memberRows).length} members · ${Object.values(view.memberRows).filter((r) => r.c).length + view.orphanClusters.length} clusters · ${view.papers.length} papers · ${(body.length / 1024).toFixed(1)} KB`,
  );
}
