#!/usr/bin/env bun
/**
 * P3 live ingest — HF daily_papers + arXiv Atom enrich + OpenAlex Papers enrich + Crossref DOI enrich + HN Algolia Pulse + lab RSS + security RSS + GitHub shelf + Wikidata DENY grounding + watchlist plan + toolkit shelf.
 * Cycle stays 003 / hf-incident. No Zapier. No paid X / api.x.com. arXiv/HN/RSS never Brief pins.
 *
 * Usage:
 *   bun run ingest
 *   bun run ingest -- --dry-run
 *
 * Offline / missing keys:
 *   - HF public API attempted when network allows
 *   - Watchlist queries logged as curation plan only (no live X)
 *   - Crawl stamp always updates when the job completes (clears STALE)
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  buildHandleQueries,
  buildSemanticQueries,
  HF_DAILY_PAPERS_URL,
  isAgentPaper,
  mergeDailyPapers,
  normalizeHfRow,
  scoreUrlList,
  xIngestEnv,
  type Paper,
} from "../src/lib/ingest/index";
import {
  applyArxivEnrichment,
  fetchArxivByIds,
  fetchArxivSearch,
  resolveArxivCacheDir,
  toShelfItems,
} from "../src/lib/arxiv-enrich";
import {
  fetchOpenAlexEnrich,
  mergeOntoPapers,
  OPENALEX_API,
  resetOpenAlexTickState,
  resolveOpenAlexCacheDir,
} from "../src/lib/openalex-enrich";
import {
  fetchCrossrefEnrich,
  mergeOntoPapers as mergeCrossrefOntoPapers,
  CROSSREF_API,
  resetCrossrefTickState,
  resolveCrossrefCacheDir,
} from "../src/lib/crossref-enrich";
import {
  fetchHnPulse,
  resolveHnCacheDir,
  type HnPulseCandidate,
} from "../src/lib/hn-pulse";
import {
  fetchRssLabs,
  resolveRssCacheDir,
  toShelfItems as rssToShelfItems,
  type LabRssItem,
} from "../src/lib/rss-labs";
import {
  fetchRssSecurity,
  resolveSecRssCacheDir,
  toSecShelfItems,
  type SecurityRssItem,
} from "../src/lib/rss-security";
import {
  fetchGithubShelf,
  resolveGithubCacheDir,
  resetGithubShelfTickState,
  toGithubShelfItems,
} from "../src/lib/github-shelf";
import {
  fetchWikidataDeny,
  resetWikidataDenyTickState,
  resolveWikidataCacheDir,
  WIKIDATA_API,
  type WikidataDenyHint,
} from "../src/lib/wikidata-deny";
import { PAPERS as KEPT_PAPERS } from "../src/data/papers";
import { SHELF as KEPT_SHELF } from "../src/data/shelf";
import { crawlAgeHours, STALE_HOURS } from "../src/lib/x-pulse";

const root = resolve(import.meta.dir, "..");
const dryRun = process.argv.includes("--dry-run");

function isoNow(): string {
  return new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
}

function writeText(path: string, body: string) {
  mkdirSync(dirname(path), { recursive: true });
  if (dryRun) {
    console.log(`[dry-run] would write ${path} (${body.length} bytes)`);
    return;
  }
  writeFileSync(path, body);
  console.log(`wrote ${path}`);
}

function renderPapersTs(papers: Paper[]): string {
  const rows = papers
    .map((p) => {
      const extras: string[] = [];
      if (p.abstract) extras.push(`,\n    abstract: ${JSON.stringify(p.abstract.slice(0, 800))}`);
      if (p.pdfUrl) extras.push(`,\n    pdfUrl: ${JSON.stringify(p.pdfUrl)}`);
      if (p.primaryCategory) extras.push(`,\n    primaryCategory: ${JSON.stringify(p.primaryCategory)}`);
      if (p.authors?.length) extras.push(`,\n    authors: ${JSON.stringify(p.authors)}`);
      if (p.doi) extras.push(`,\n    doi: ${JSON.stringify(p.doi)}`);
      if (p.year != null) extras.push(`,\n    year: ${p.year}`);
      if (p.openalexId) extras.push(`,\n    openalexId: ${JSON.stringify(p.openalexId)}`);
      if (p.openalexEnrichOnly) extras.push(`,\n    openalexEnrichOnly: true`);
      if (p.crossrefDoi) extras.push(`,\n    crossrefDoi: ${JSON.stringify(p.crossrefDoi)}`);
      if (p.crossrefIssued) extras.push(`,\n    crossrefIssued: ${JSON.stringify(p.crossrefIssued)}`);
      if (p.crossrefType) extras.push(`,\n    crossrefType: ${JSON.stringify(p.crossrefType)}`);
      if (p.crossrefUrl) extras.push(`,\n    crossrefUrl: ${JSON.stringify(p.crossrefUrl)}`);
      if (p.crossrefEnrichOnly) extras.push(`,\n    crossrefEnrichOnly: true`);
      return `  { id: ${JSON.stringify(p.id)}, title: ${JSON.stringify(p.title)}, up: ${p.up}, href: ${JSON.stringify(p.href)}${extras.join("")} }`;
    })
    .join(",\n");
  return `/** Generated by bun run ingest — HF daily_papers + arXiv enrich + OpenAlex Papers enrich + Crossref DOI enrich (gen/sim displacement rule applied). */\nexport const PAPERS = [\n${rows},\n];\n`;
}

function renderShelfTs(
  items: { href: string; label: string; reason: string }[],
): string {
  const rows = items
    .map(
      (i) =>
        `  { href: ${JSON.stringify(i.href)}, label: ${JSON.stringify(i.label)}, reason: ${JSON.stringify(i.reason)} as const }`,
    )
    .join(",\n");
  return `/** Operator toolkit + arXiv/RSS shelf — off Brief. Refresh via bun run ingest. */\nexport type ShelfItem = {\n  href: string;\n  label: string;\n  reason: "toolkit" | "toolkit-github" | "arxiv-shelf" | "rss-lab-shelf" | "rss-security-shelf" | "github-search-shelf";\n};\n\nexport const SHELF: ShelfItem[] = [\n${rows},\n];\n`;
}

function renderHnPulseTs(rows: HnPulseCandidate[], stamp: string): string {
  const body = rows
    .map((r) => {
      return `  { id: ${JSON.stringify(r.id)}, text: ${JSON.stringify(r.text)}, url: ${JSON.stringify(r.url)}, source: "hn-algolia" as const, score: ${r.score}, at: ${JSON.stringify(r.at)}, author: ${JSON.stringify(r.author)}, tag: ${JSON.stringify(r.tag)} as const }`;
    })
    .join(",\n");
  return `/** HN Algolia Pulse chatter — generated/refreshed by bun run ingest. Pulse only; never Brief. */
export type HnPulseRow = {
  id: string;
  text: string;
  url: string;
  source: "hn-algolia";
  score: number;
  at: string;
  author: string;
  tag: "rest" | "rumor" | "companion" | "incident";
};

export const HN_PULSE_AT = ${JSON.stringify(stamp)};

export const HN_PULSE: HnPulseRow[] = [
${body},
];
`;
}

function renderRssLabsTs(rows: LabRssItem[], stamp: string): string {
  const body = rows
    .map((r) => {
      return `  { id: ${JSON.stringify(r.id)}, lab: ${JSON.stringify(r.lab)} as const, title: ${JSON.stringify(r.title)}, link: ${JSON.stringify(r.link)}, published: ${JSON.stringify(r.published)}, summary: ${JSON.stringify(r.summary)}, source: "rss-lab" as const, tag: ${JSON.stringify(r.tag)} as const }`;
    })
    .join(",\n");
  return `/** Lab blog RSS Pulse — generated/refreshed by bun run ingest. Pulse/shelf only; never Brief. */
export type RssLabRow = {
  id: string;
  lab: "openai" | "deepmind" | "google-ai" | "huggingface" | "mistral" | "nvidia" | "nvidia-dev" | "ms-research" | "google-research";
  title: string;
  link: string;
  published: string;
  summary: string;
  source: "rss-lab";
  tag: "rest" | "rumor" | "companion" | "incident";
};

export const RSS_LABS_AT = ${JSON.stringify(stamp)};

export const RSS_LABS: RssLabRow[] = [
${body},
];
`;
}

function renderRssSecurityTs(rows: SecurityRssItem[], stamp: string): string {
  const body = rows
    .map((r) => {
      return `  { id: ${JSON.stringify(r.id)}, lab: ${JSON.stringify(r.lab)} as const, title: ${JSON.stringify(r.title)}, link: ${JSON.stringify(r.link)}, published: ${JSON.stringify(r.published)}, summary: ${JSON.stringify(r.summary)}, source: "rss-security" as const, tag: ${JSON.stringify(r.tag)} as const }`;
    })
    .join(",\n");
  return `/** Security lab RSS Pulse — generated/refreshed by bun run ingest. Pulse/shelf/Digest-ref only; never Brief. */
export type RssSecurityRow = {
  id: string;
  lab: "trailofbits" | "fox-it" | "ncc" | "projectzero" | "google-sec";
  title: string;
  link: string;
  published: string;
  summary: string;
  source: "rss-security";
  tag: "rest" | "rumor" | "companion" | "incident";
};

export const RSS_SECURITY_AT = ${JSON.stringify(stamp)};

export const RSS_SECURITY: RssSecurityRow[] = [
${body},
];
`;
}

function patchCrawlAt(src: string, stamp: string): string {
  if (/export const CRAWL_AT = "[^"]+"/.test(src)) {
    return src.replace(/export const CRAWL_AT = "[^"]+"/, `export const CRAWL_AT = "${stamp}"`);
  }
  throw new Error("x-crawl.ts missing CRAWL_AT export");
}

function patchCurrentJson(path: string, stamp: string) {
  const data = JSON.parse(readFileSync(path, "utf8"));
  if (data.id !== "003") {
    throw new Error(`refuse ingest: cycle id is ${data.id}, expected 003`);
  }
  data.crawled_at = stamp;
  data.compiled_at = data.compiled_at ?? stamp;
  data.ingest_note =
    "P3 ingest stamp. Lead remains hf-incident. Free providers only (HF daily_papers + arXiv Atom + OpenAlex Papers enrich + Crossref DOI enrich + HN Algolia Pulse + lab RSS + security RSS ToB/Fox-IT/PZ + GitHub unauth shelf + Wikidata DENY grounding + shelf). No paid X. arXiv/OpenAlex/Crossref/HN/RSS/GitHub/Wikidata never Brief pins. HF HTML fallback not wired. NCC RSS skip. S2 deferred.";
  writeText(path, `${JSON.stringify(data, null, 2)}\n`);
}

async function fetchHfPapers(): Promise<Paper[]> {
  const res = await fetch(HF_DAILY_PAPERS_URL, {
    headers: { Accept: "application/json" },
  });
  if (!res.ok) throw new Error(`HF daily_papers HTTP ${res.status}`);
  const raw = (await res.json()) as unknown[];
  const papers: Paper[] = [];
  for (const row of raw) {
    const p = normalizeHfRow(row);
    if (p) papers.push(p);
  }
  return papers;
}

function loadUrlList(): string[] {
  const candidates = [
    resolve(root, "../sage-handoff/attachments/fancyTWEETScuration0209.txt"),
    resolve(root, "../../attachments/fancyTWEETScuration0209.txt"),
    resolve("/workspace/attachments/fancyTWEETScuration0209.txt"),
  ];
  for (const p of candidates) {
    if (existsSync(p)) {
      console.log(`URL list: ${p}`);
      return readFileSync(p, "utf8")
        .split(/\r?\n/)
        .map((l) => l.trim())
        .filter(Boolean);
    }
  }
  console.log("URL list: not found — shelf kept as-is / empty score");
  return [];
}

async function main() {
  const stamp = isoNow();
  console.log(`SAGE ingest P3 · stamp ${stamp} · STALE_HOURS=${STALE_HOURS}`);

  const since = buildHandleQueries()[0]?.query.match(/since:(\d{4}-\d{2}-\d{2})/)?.[1] ?? "";
  const handleQs = buildHandleQueries(3);
  const semanticQs = buildSemanticQueries();
  console.log(
    `Watchlist plan (curation only, no live X): ${handleQs.length} handles (weight≥3) + ${semanticQs.length} semantic classes since ${since || "yesterday"}`,
  );
  for (const h of handleQs.slice(0, 3)) console.log(`  handle ${h.handle} w=${h.weight} :: ${h.query}`);
  for (const s of semanticQs) console.log(`  class ${s.class} :: ${s.query}`);

  const xEnv = xIngestEnv();
  console.log(`X: disabled (${xEnv.docs})`);

  let papers: Paper[] = KEPT_PAPERS.map((p) => {
    const row = p as Paper;
    return {
      id: row.id,
      title: row.title,
      up: row.up,
      href: row.href,
      abstract: row.abstract,
      pdfUrl: row.pdfUrl,
      authors: row.authors,
      primaryCategory: row.primaryCategory,
      doi: row.doi,
      year: row.year,
      openalexId: row.openalexId,
      openalexEnrichOnly: row.openalexEnrichOnly,
      crossrefDoi: row.crossrefDoi,
      crossrefIssued: row.crossrefIssued,
      crossrefType: row.crossrefType,
      crossrefUrl: row.crossrefUrl,
      crossrefEnrichOnly: row.crossrefEnrichOnly,
    };
  });
  let hfOk = false;
  try {
    const live = await fetchHfPapers();
    const keptAgent = papers.filter(isAgentPaper);
    papers = mergeDailyPapers(live, { keptAgent, limit: 8 });
    hfOk = true;
    console.log(`HF: ${live.length} live → ${papers.length} kept (displacement rule applied)`);
  } catch (err) {
    console.log(`HF: fetch failed — keeping existing papers (${String(err)})`);
  }

  // arXiv Atom enrich AFTER HF merge — Papers abstracts/links only; never Brief pins / never cycle 004
  let arxivOk = false;
  let arxivCount = 0;
  let arxivShelf: { href: string; label: string; reason: "arxiv-shelf" }[] = [];
  try {
    const enrichments = await fetchArxivByIds(
      papers.map((p) => p.id),
      { cacheDir: resolveArxivCacheDir(root), maxResults: 25 },
    );
    if (enrichments.length) {
      papers = applyArxivEnrichment(papers, enrichments);
      arxivOk = true;
      arxivCount = enrichments.length;
      console.log(`arXiv: enriched ${arxivCount}/${papers.length} paper ids (cache+live)`);
    } else {
      console.log("arXiv: no enrichments (skip / empty)");
    }
    // Optional shelf-only search hits (not already HF keeps)
    const searchHits = await fetchArxivSearch({ maxResults: 5 });
    arxivShelf = toShelfItems(
      searchHits,
      papers.map((p) => p.id),
    ).map((s) => ({ href: s.href, label: s.label, reason: "arxiv-shelf" as const }));
    if (arxivShelf.length) {
      console.log(`arXiv shelf: ${arxivShelf.length} search hits (shelfOnly, off Brief)`);
    }
  } catch (err) {
    console.log(`arXiv: enrich failed — continuing (${String(err)})`);
  }

  // OpenAlex Papers enrich AFTER arXiv — id/year/DOI metadata only; never Brief / never Pulse lead / never displace HF keeps
  resetOpenAlexTickState();
  let openalexOk = false;
  let openalexSoftFail = false;
  let openalexSoftFailReason: string | undefined;
  let openalexCount = 0;
  let openalexSecondary = 0;
  let openalexQuery = "";
  let openalexFromCache = false;
  let openalexSearches = 0;
  let openalexRetries = 0;
  let openalexMode: string = "search";
  try {
    const oa = await fetchOpenAlexEnrich({
      papers,
      cacheDir: resolveOpenAlexCacheDir(root),
    });
    openalexQuery = oa.query;
    openalexFromCache = oa.from_cache;
    openalexSearches = oa.searches;
    openalexRetries = oa.retries;
    openalexSoftFail = oa.soft_fail;
    openalexSoftFailReason = oa.soft_fail_reason;
    openalexMode = oa.mode;
    if (oa.soft_fail) {
      console.log(
        `OpenAlex: soft-fail (${oa.soft_fail_reason ?? "unknown"}) retries=${oa.retries} enriched=0 — continuing stamp (brief=false)`,
      );
    } else if (oa.enrichments.length) {
      const beforeIds = new Set(papers.map((p) => p.id));
      const agentBefore = papers.filter(isAgentPaper).map((p) => p.id);
      papers = mergeOntoPapers(papers, oa.enrichments, {
        // Room for a few enrich-only secondaries without displacing HF keeps
        limit: Math.max(8, papers.length) + 3,
      });
      // Displacement guard: every prior agent keep must remain
      for (const id of agentBefore) {
        if (!papers.some((p) => p.id === id)) {
          throw new Error(`OpenAlex displaced HF agent keep ${id}`);
        }
      }
      openalexOk = true;
      openalexCount = papers.filter((p) => p.openalexId).length;
      openalexSecondary = papers.filter((p) => p.openalexEnrichOnly).length;
      console.log(
        `OpenAlex: enriched=${openalexCount} secondary=${openalexSecondary} mode=${oa.mode} cache=${oa.from_cache} retries=${oa.retries} brief=false pulse_lead=false`,
      );
      void beforeIds;
    } else {
      console.log("OpenAlex: no enrichments (skip / empty)");
    }
  } catch (err) {
    openalexSoftFail = true;
    openalexSoftFailReason = String(err);
    console.log(`OpenAlex: soft-fail exception — continuing (${String(err)})`);
  }

  // Crossref Papers DOI enrich AFTER OpenAlex — filter=doi:/bibliographic only; never Brief / never Pulse lead / never displace HF keeps
  resetCrossrefTickState();
  let crossrefOk = false;
  let crossrefSoftFail = false;
  let crossrefSoftFailReason: string | undefined;
  let crossrefCount = 0;
  let crossrefQuery = "";
  let crossrefFromCache = false;
  let crossrefSearches = 0;
  let crossrefMode: string = "bibliographic";
  let crossrefMergeNotes: string[] = [];
  try {
    const cr = await fetchCrossrefEnrich({
      papers,
      cacheDir: resolveCrossrefCacheDir(root),
    });
    crossrefQuery = cr.query;
    crossrefFromCache = cr.from_cache;
    crossrefSearches = cr.searches;
    crossrefSoftFail = cr.soft_fail;
    crossrefSoftFailReason = cr.soft_fail_reason;
    crossrefMode = cr.mode;
    if (cr.soft_fail) {
      console.log(
        `Crossref: soft-fail (${cr.soft_fail_reason ?? "unknown"}) — continuing stamp (brief=false)`,
      );
    } else if (cr.enrichments.length) {
      const agentBefore = papers.filter(isAgentPaper).map((p) => p.id);
      const merged = mergeCrossrefOntoPapers(papers, cr.enrichments, {
        limit: Math.max(8, papers.length) + 3,
        allowSecondary: false,
      });
      papers = merged.papers;
      crossrefMergeNotes = merged.notes;
      for (const id of agentBefore) {
        if (!papers.some((p) => p.id === id)) {
          throw new Error(`Crossref displaced HF agent keep ${id}`);
        }
      }
      // openalexId must survive non-destructive merge
      crossrefOk = true;
      crossrefCount = papers.filter((p) => p.crossrefDoi).length;
      console.log(
        `Crossref: enriched=${crossrefCount} mode=${cr.mode} cache=${cr.from_cache} brief=false pulse_lead=false notes=${crossrefMergeNotes.length}`,
      );
      for (const n of crossrefMergeNotes.slice(0, 3)) {
        console.log(`  crossref note: ${n}`);
      }
    } else {
      console.log("Crossref: no enrichments (skip / empty)");
    }
  } catch (err) {
    crossrefSoftFail = true;
    crossrefSoftFailReason = String(err);
    console.log(`Crossref: soft-fail exception — continuing (${String(err)})`);
  }

  // HN Algolia AFTER Crossref — Pulse chatter only; never Brief lead/companion / never toolkit Brief pins
  let hnOk = false;
  let hnRows: HnPulseCandidate[] = [];
  try {
    hnRows = await fetchHnPulse({
      cacheDir: resolveHnCacheDir(root),
      hitsPerPage: 10,
    });
    hnOk = hnRows.length > 0;
    console.log(
      `HN: ${hnRows.length} Pulse candidates (classifyPost filtered; brief=false)`,
    );
    for (const h of hnRows.slice(0, 3)) {
      console.log(`  hn ${h.id} [${h.tag}] score=${h.score} :: ${h.text.slice(0, 72)}`);
    }
  } catch (err) {
    console.log(`HN: fetch failed — continuing (${String(err)})`);
  }

  // Lab RSS AFTER HN — Pulse/shelf only; never Brief lead / never cycle 004 / never displace HF
  let rssOk = false;
  let rssSoftFail = false;
  let rssSoftFailReason: string | undefined;
  let rssPulse: LabRssItem[] = [];
  let rssShelf: { href: string; label: string; reason: "rss-lab-shelf" }[] = [];
  let rssFeedsOk: { lab: string; url: string; count: number }[] = [];
  let rssFeedsSoftFail: { lab: string; reason: string; soft_fail: true }[] = [];
  try {
    const rss = await fetchRssLabs({
      cacheDir: resolveRssCacheDir(root),
      maxPerFeed: 12,
    });
    rssPulse = rss.pulse;
    rssShelf = rssToShelfItems(rss.shelf);
    rssFeedsOk = rss.feedsOk;
    rssFeedsSoftFail = rss.feedsSoftFail;
    rssSoftFail = rss.soft_fail;
    rssSoftFailReason = rss.soft_fail_reason;
    rssOk = rss.ok;
    console.log(
      `RSS labs: ${rss.pulse.length} Pulse + ${rss.shelf.length} shelf from ${rss.feedsOk.length} feeds soft_fail=${rss.soft_fail} (brief=false · never HF displace)`,
    );
    for (const f of rss.feedsOk) {
      console.log(`  rss ${f.lab} @ ${f.url} → ${f.count} items`);
    }
    for (const s of rss.feedsSoftFail) {
      console.log(`  rss soft_fail ${s.lab}: ${s.reason}`);
    }
    for (const it of rss.pulse.slice(0, 3)) {
      console.log(`  rss ${it.lab} [${it.tag}] :: ${it.title.slice(0, 72)}`);
    }
  } catch (err) {
    rssSoftFail = true;
    rssSoftFailReason = `exception: ${String(err)}`;
    console.log(`RSS labs: soft_fail — continuing (${String(err)})`);
  }

  // Security lab RSS AFTER lab RSS — Pulse/shelf/Digest-ref; never Brief lead / never cycle 004
  let secOk = false;
  let secPulse: SecurityRssItem[] = [];
  let secShelf: { href: string; label: string; reason: "rss-security-shelf" }[] = [];
  let secFeedsOk: { lab: string; url: string; count: number }[] = [];
  try {
    const sec = await fetchRssSecurity({
      cacheDir: resolveSecRssCacheDir(root),
      maxPerFeed: 12,
    });
    secPulse = sec.pulse;
    secShelf = toSecShelfItems(sec.shelf);
    secFeedsOk = sec.feedsOk;
    secOk = sec.feedsOk.length >= 1;
    console.log(
      `RSS security: ${sec.pulse.length} Pulse + ${sec.shelf.length} shelf from ${sec.feedsOk.length} feeds (brief=false)`,
    );
    for (const f of sec.feedsOk) {
      console.log(`  rss-sec ${f.lab} @ ${f.url} → ${f.count} items`);
    }
    for (const s of sec.feedsSkipped) {
      console.log(`  rss-sec skip ${s.lab}: ${s.reason}`);
    }
    for (const it of sec.pulse.slice(0, 3)) {
      console.log(`  rss-sec ${it.lab} [${it.tag}] :: ${it.title.slice(0, 72)}`);
    }
  } catch (err) {
    console.log(`RSS security: fetch failed — continuing (${String(err)})`);
  }

  // GitHub unauth search AFTER security RSS — shelf only; never Brief / never Pulse lead / never cycle 004
  resetGithubShelfTickState();
  let githubOk = false;
  let githubSoftFail = false;
  let githubSoftFailReason: string | undefined;
  let githubShelf: { href: string; label: string; reason: "github-search-shelf" }[] = [];
  let githubQuery = "";
  let githubFromCache = false;
  let githubSearches = 0;
  try {
    const gh = await fetchGithubShelf({
      cacheDir: resolveGithubCacheDir(root),
    });
    githubQuery = gh.query;
    githubFromCache = gh.from_cache;
    githubSearches = gh.searches;
    githubSoftFail = gh.soft_fail;
    githubSoftFailReason = gh.soft_fail_reason;
    if (gh.soft_fail) {
      console.log(
        `GitHub shelf: soft-fail (${gh.soft_fail_reason ?? "unknown"}) — continuing stamp`,
      );
    } else {
      githubShelf = toGithubShelfItems(gh.shelf);
      githubOk = gh.ok && githubShelf.length >= 0;
      console.log(
        `GitHub shelf: query="${gh.query}" hits=${gh.hits.length} shelf=${githubShelf.length} cache=${gh.from_cache} searches=${gh.searches} brief=false`,
      );
      for (const s of githubShelf.slice(0, 3)) {
        console.log(`  gh-shelf ${s.label} :: ${s.href}`);
      }
    }
  } catch (err) {
    githubSoftFail = true;
    githubSoftFailReason = String(err);
    console.log(`GitHub shelf: soft-fail exception — continuing (${String(err)})`);
  }


  // Wikidata DENY grounding AFTER GitHub — hygiene only; never Brief / never Pulse lead / never invent pins
  resetWikidataDenyTickState();
  let wikidataOk = false;
  let wikidataSoftFail = false;
  let wikidataSoftFailReason: string | undefined;
  let wikidataHints: WikidataDenyHint[] = [];
  let wikidataFromCache = false;
  let wikidataSearches = 0;
  let wikidataSeedsTried: string[] = [];
  try {
    const wd = await fetchWikidataDeny({
      cacheDir: resolveWikidataCacheDir(root),
    });
    wikidataHints = wd.hints;
    wikidataFromCache = wd.from_cache;
    wikidataSearches = wd.searches;
    wikidataSeedsTried = wd.seeds_tried;
    wikidataSoftFail = wd.soft_fail;
    wikidataSoftFailReason = wd.soft_fail_reason;
    wikidataOk = wd.ok;
    if (wd.soft_fail) {
      console.log(
        `Wikidata DENY: soft-fail (${wd.soft_fail_reason ?? "unknown"}) — continuing stamp (brief=false)`,
      );
    } else {
      console.log(
        `Wikidata DENY: seeds=${wd.seeds_tried.join(",")} hints=${wd.hints.length} cache=${wd.from_cache} searches=${wd.searches} brief=false`,
      );
      for (const h of wd.hints.slice(0, 4)) {
        console.log(
          `  wd ${h.seed} [${h.status}] qid=${h.qid ?? "null"} :: ${(h.label ?? "").slice(0, 56)}`,
        );
      }
    }
  } catch (err) {
    wikidataSoftFail = true;
    wikidataSoftFailReason = String(err);
    console.log(`Wikidata DENY: soft-fail exception — continuing (${String(err)})`);
  }

  const urls = loadUrlList();
  const scored = scoreUrlList(urls);
  const toolkitShelf = scored.shelf.length
    ? scored.shelf.map((s) => ({
        href: s.href,
        label: s.href.replace(/^https?:\/\//, "").slice(0, 72),
        reason:
          s.reason === "toolkit-github"
            ? ("toolkit-github" as const)
            : ("toolkit" as const),
      }))
    : KEPT_SHELF.filter(
          (s) =>
            s.reason !== "arxiv-shelf" &&
            s.reason !== "rss-lab-shelf" &&
            s.reason !== "rss-security-shelf" &&
            s.reason !== "github-search-shelf",
        ).map((s) => ({
        href: s.href,
        label: s.label,
        reason: s.reason as "toolkit" | "toolkit-github",
      }));
  const shelfItems = [
    ...toolkitShelf,
    ...arxivShelf,
    ...rssShelf,
    ...secShelf,
    ...githubShelf,
  ];
  const shelfDirty =
    scored.shelf.length > 0 ||
    arxivShelf.length > 0 ||
    rssShelf.length > 0 ||
    secShelf.length > 0 ||
    githubShelf.length > 0;
  console.log(
    `URL score: shelf=${scored.shelf.length} pulse=${scored.pulse.length} rest=${scored.rest.length} drop=${scored.dropped.length} arxivShelf=${arxivShelf.length} rssShelf=${rssShelf.length} secShelf=${secShelf.length} githubShelf=${githubShelf.length}`,
  );

  // Stamp pulse — job ran
  const crawlPath = resolve(root, "src/data/x-crawl.ts");
  const crawlSrc = readFileSync(crawlPath, "utf8");
  writeText(crawlPath, patchCrawlAt(crawlSrc, stamp));
  patchCurrentJson(resolve(root, "artifacts/sage/CURRENT.json"), stamp);

  if (hfOk || arxivOk || openalexOk || crossrefOk) {
    writeText(resolve(root, "src/data/papers.ts"), renderPapersTs(papers));
  }
  if (shelfDirty) {
    writeText(resolve(root, "src/data/shelf.ts"), renderShelfTs(shelfItems));
  }
  if (hnOk) {
    writeText(resolve(root, "src/data/hn-pulse.ts"), renderHnPulseTs(hnRows, stamp));
  }
  if (rssOk) {
    writeText(resolve(root, "src/data/rss-labs.ts"), renderRssLabsTs(rssPulse, stamp));
  }
  if (secOk) {
    writeText(
      resolve(root, "src/data/rss-security.ts"),
      renderRssSecurityTs(secPulse, stamp),
    );
  }

  const report = {
    schema: 1,
    cycle: "003",
    lead_id: "hf-incident",
    stamped_at: stamp,
    stale_hours: STALE_HOURS,
    age_check: crawlAgeHours(stamp),
    hf: { ok: hfOk, count: papers.length, url: HF_DAILY_PAPERS_URL },
    arxiv: {
      ok: arxivOk,
      enriched: arxivCount,
      shelf: arxivShelf.length,
      brief: false,
      url: "https://export.arxiv.org/api/query",
    },
    openalex: {
      ok: openalexOk,
      soft_fail: openalexSoftFail,
      soft_fail_reason: openalexSoftFailReason ?? null,
      enriched: openalexCount,
      secondary: openalexSecondary,
      query: openalexQuery,
      mode: openalexMode,
      from_cache: openalexFromCache,
      searches: openalexSearches,
      retries: openalexRetries,
      brief: false,
      pulse_lead: false,
      papers_enrich_only: true,
      url: OPENALEX_API,
      sample: papers
        .filter((p) => p.openalexId)
        .slice(0, 3)
        .map((p) => ({
          id: p.id,
          openalexId: p.openalexId,
          year: p.year ?? null,
          doi: p.doi ?? null,
          enrichOnly: Boolean(p.openalexEnrichOnly),
        })),
    },
    crossref: {
      ok: crossrefOk,
      soft_fail: crossrefSoftFail,
      soft_fail_reason: crossrefSoftFailReason ?? null,
      enriched: crossrefCount,
      query: crossrefQuery,
      mode: crossrefMode,
      from_cache: crossrefFromCache,
      searches: crossrefSearches,
      brief: false,
      pulse_lead: false,
      papers_enrich_only: true,
      url: CROSSREF_API,
      merge_notes: crossrefMergeNotes,
      sample: papers
        .filter((p) => p.crossrefDoi)
        .slice(0, 3)
        .map((p) => ({
          id: p.id,
          crossrefDoi: p.crossrefDoi,
          issued: p.crossrefIssued ?? null,
          type: p.crossrefType ?? null,
          openalexId: p.openalexId ?? null,
          doi: p.doi ?? null,
          enrichOnly: Boolean(p.crossrefEnrichOnly),
        })),
    },
    hn: {
      ok: hnOk,
      count: hnRows.length,
      brief: false,
      pulse_only: true,
      url: "https://hn.algolia.com/api/v1/search",
      sample: hnRows.slice(0, 3).map((h) => ({ id: h.id, tag: h.tag, score: h.score, text: h.text })),
    },
    rss: {
      ok: rssOk,
      soft_fail: rssSoftFail,
      soft_fail_reason: rssSoftFailReason ?? null,
      count: rssPulse.length,
      shelf: rssShelf.length,
      brief: false,
      pulse_only: true,
      never_displace_hf: true,
      feeds: rssFeedsOk,
      feeds_soft_fail: rssFeedsSoftFail,
      sample: rssPulse.slice(0, 4).map((r) => ({
        id: r.id,
        lab: r.lab,
        tag: r.tag,
        title: r.title,
        link: r.link,
      })),
    },
    rss_security: {
      ok: secOk,
      count: secPulse.length,
      shelf: secShelf.length,
      brief: false,
      pulse_only: true,
      digest_ref_ok: true,
      feeds: secFeedsOk,
      sample: secPulse.slice(0, 4).map((r) => ({
        id: r.id,
        lab: r.lab,
        tag: r.tag,
        title: r.title,
        link: r.link,
      })),
    },
    x: {
      fetched: 0,
      skipped: true as const,
      disabled: true as const,
      handles: handleQs.length,
      semantic: semanticQs.length,
      plug_in: xEnv.docs,
    },
    github: {
      ok: githubOk,
      soft_fail: githubSoftFail,
      soft_fail_reason: githubSoftFailReason ?? null,
      query: githubQuery,
      shelf: githubShelf.length,
      from_cache: githubFromCache,
      searches: githubSearches,
      brief: false,
      pulse_lead: false,
      url: "https://api.github.com/search/repositories",
      sample: githubShelf.slice(0, 3).map((s) => ({
        label: s.label,
        href: s.href,
      })),
    },
    shelf: { count: shelfItems.length, brief: false },
    wikidata: {
      ok: wikidataOk,
      soft_fail: wikidataSoftFail,
      soft_fail_reason: wikidataSoftFailReason ?? null,
      seeds: wikidataSeedsTried,
      searches: wikidataSearches,
      from_cache: wikidataFromCache,
      brief: false,
      pulse_lead: false,
      deny_grounding_only: true,
      url: WIKIDATA_API,
      hints: wikidataHints.map((h) => ({
        seed: h.seed,
        qid: h.qid,
        label: h.label,
        description: h.description,
        status: h.status,
        source: h.source,
        briefEligible: false as const,
        pulseLeadEligible: false as const,
        denyGroundingOnly: true as const,
      })),
    },
    locks: {
      cycle: "003",
      lead: "hf-incident",
      no_zapier: true,
      no_paid_x: true,
      green_token: "--phosphor",
      stale_class: ".sage-stale",
    },
  };
  writeText(
    resolve(root, "artifacts/sage/ingest-last.json"),
    `${JSON.stringify(report, null, 2)}\n`,
  );

  const proof = crawlAgeHours(stamp);
  console.log(
    proof.stale
      ? `STALE proof: age ${proof.hours.toFixed(2)}h > ${STALE_HOURS}h → .sage-stale`
      : `STALE proof: fresh stamp age ${proof.hours.toFixed(2)}h ≤ ${STALE_HOURS}h (banner clear)`,
  );
  console.log("Done. Pulse reads CRAWL_AT; banner uses crawlAgeHours + .sage-stale.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
