#!/usr/bin/env bun
/**
 * Beat 4 — corroboration rank snapshot. Runs after every real ingest (npm `postingest`).
 * Reads the freshly written data modules, ranks curated Brief/Digest items below the
 * pinned lead, rotates artifacts/sage/rank-last.json → rank-prev.json (only when the
 * crawl stamp changed), writes the new rank-last.json and src/data/corroboration-rank.ts.
 * Beat 7: also rotates artifacts/sage/wire-last.json → wire-prev.json (same crawl-stamp rule) and
 * writes src/data/wire.ts — the Brief Wire strip (top 3–5 multi-source clusters, NEW/▲/▼ vs prev).
 * Beat 7 daily lead: appends to artifacts/sage/lead-history.json when today's pick is absent AND
 * (crawl is in the 06:xx Istanbul window OR LEAD_PICK_FORCE=1); writes src/data/lead-pick.ts.
 * No HTTP. Exits 1 if the lead is not hf-* (cycle 003 lock).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { DIGEST_ITEMS } from "@/data/digest-pack";
import { PULSE_CLUSTERS, PULSE_CLUSTERS_AT } from "@/data/pulse-clusters";
import { GNEWS_RSS } from "@/data/gnews-rss";
import { HN_PULSE } from "@/data/hn-pulse";
import { RSS_LABS } from "@/data/rss-labs";
import { RSS_SECURITY } from "@/data/rss-security";
import { X_TASTE } from "@/data/x-taste";
import { diffSnapshots, rankBelowLead, toSnapshot, type RankSnapshot } from "@/lib/corroboration";
import { CYCLE } from "@/data/cycle";
import { applyPick, currentLead, groupFirstAt, leadExcludeReason, decidePick, istanbulDate, readLeadHistory, yesterdayLead, type LeadHistory } from "@/lib/lead-pick";
import { buildWire, readWireSnapshot, wireCounts, wireHeader, wireMark, type WireSnapshot } from "@/lib/wire";

const desk = resolve(import.meta.dir, "..");
const dir = resolve(desk, "artifacts/sage");
const lastPath = resolve(dir, "rank-last.json");
const prevPath = resolve(dir, "rank-prev.json");
const dataPath = resolve(desk, "src/data/corroboration-rank.ts");

function readSnap(p: string): RankSnapshot | null {
  if (!existsSync(p)) return null;
  try {
    const j = JSON.parse(readFileSync(p, "utf8")) as RankSnapshot;
    return j && j.schema === 1 && Array.isArray(j.rows) ? j : null;
  } catch {
    return null;
  }
}

const rows = rankBelowLead(DIGEST_ITEMS, { clusters: PULSE_CLUSTERS, leadId: "hf-incident" });
const lead = rows.find((r) => r.lead);
if (!lead || !/hf/.test(lead.id)) {
  console.error(`rank-snapshot FAIL: lead is ${lead?.id ?? "(none)"} — cycle 003 locks hf-incident`);
  process.exit(1);
}
const cur = toSnapshot(rows, new Date().toISOString(), PULSE_CLUSTERS_AT);

mkdirSync(dir, { recursive: true });
const oldLast = readSnap(lastPath);
let prev = readSnap(prevPath);
if (oldLast && oldLast.crawl_at !== cur.crawl_at) {
  prev = oldLast;
  writeFileSync(prevPath, JSON.stringify(oldLast, null, 2) + "\n");
}
writeFileSync(lastPath, JSON.stringify(cur, null, 2) + "\n");
const moved = diffSnapshots(prev, cur);

const body = `/** Beat 4 corroboration rank — generated by scripts/rank-snapshot.ts (npm postingest). Curated Brief/Digest items only; lead pinned. */
import type { MovedRow, RankSnapshot } from "@/lib/corroboration";

export const RANK_CURRENT: RankSnapshot = ${JSON.stringify(cur, null, 2)};

export const RANK_PREV: RankSnapshot | null = ${JSON.stringify(prev, null, 2)};

export const RANK_MOVED: MovedRow[] = ${JSON.stringify(moved, null, 2)};
`;
writeFileSync(dataPath, body);

console.log(`rank-snapshot OK crawl=${cur.crawl_at} prev=${prev?.crawl_at ?? "(none)"} lead=${cur.lead_id}`);
for (const m of moved) {
  const r = cur.rows.find((x) => x.id === m.id);
  console.log(
    `  ${m.status.padEnd(4)} ${m.id.padEnd(16)} rank ${m.prev_rank ?? "—"}→${m.rank ?? "—"} base ${r?.base_rank ?? "—"} src ${m.prev_sources ?? "—"}→${m.sources ?? "—"} ×${r?.mult ?? "—"}${m.by_corroboration ? " corroboration" : ""}`,
  );
}

const scores: Record<string, number> = {};
for (const h of HN_PULSE) scores[h.id] = h.score;

// ── Beat 7 · daily Brief lead pick (sticky 24h; HELD keeps yesterday's) ──
const historyPath = resolve(dir, "lead-history.json");
const leadDataPath = resolve(desk, "src/data/lead-pick.ts");
let history: LeadHistory = { schema: 1, entries: [] };
if (existsSync(historyPath)) {
  try {
    history = readLeadHistory(JSON.parse(readFileSync(historyPath, "utf8")));
  } catch {
    /* corrupt → start fresh below */
  }
} else {
  // One-time seed: the static cycle-003 pin (hf-incident) was the Brief lead before daily picks existed.
  const seedDay = new Date(Date.parse(PULSE_CLUSTERS_AT) - 86_400_000).toISOString();
  history = {
    schema: 1,
    entries: [
      {
        date: istanbulDate(seedDay),
        cluster_id: "hf-incident",
        headline: CYCLE.exec[0] ?? "HF production swarm",
        url: null,
        sources: 0,
        sig: null,
        reason: "seed",
        note: "cycle 003 static pin, before the daily pick existed",
        at: cur.at,
        crawl_at: PULSE_CLUSTERS_AT,
      },
    ],
  };
}
// Group age = its EARLIEST member item (late reposts never refresh an old story).
const memberAt: Record<string, string> = {};
for (const h of HN_PULSE) memberAt[h.id] = h.at;
for (const g of GNEWS_RSS) memberAt[g.id] = g.published;
for (const r of RSS_LABS) memberAt[r.id] = r.published;
for (const r of RSS_SECURITY) memberAt[r.id] = r.published;
const pickNow = Date.parse(PULSE_CLUSTERS_AT);
for (const c of leadCandidatesAll(PULSE_CLUSTERS, pickNow, { scores, memberAt, tasteIds: X_TASTE.items.map((t) => t.id) }))
  console.log(`  lead-cand ${c.id.padEnd(28)} ${c.sources} SRC sig ${c.score ?? "—"} first ${c.first} age ${c.ageH}h ${c.reason ?? "ELIGIBLE"} · ${c.title.slice(0, 60)}`);
const decision = decidePick(history, PULSE_CLUSTERS, {
  memberAt,
  crawlAt: PULSE_CLUSTERS_AT,
  at: cur.at,
  force: process.env.LEAD_PICK_FORCE === "1",
  scores,
  tasteIds: X_TASTE.items.map((t) => t.id),
});
history = applyPick(history, decision);
writeFileSync(historyPath, JSON.stringify(history, null, 2) + "\n");
const leadNow = currentLead(history);
const leadYday = yesterdayLead(history);
writeFileSync(
  leadDataPath,
  `/** Beat 7 daily Brief lead — generated by scripts/rank-snapshot.ts from artifacts/sage/lead-history.json. Picked at the 06:11 Istanbul crawl (or LEAD_PICK_FORCE=1); sticky 24h. */
import type { LeadEntry } from "@/lib/lead-pick";

export const LEAD_TODAY: LeadEntry | null = ${JSON.stringify(leadNow, null, 2)};

export const LEAD_YESTERDAY: LeadEntry | null = ${JSON.stringify(leadYday, null, 2)};

export const LEAD_HELD = ${leadNow?.reason === "held"};
`,
);
console.log(
  `lead-pick ${decision.action}${decision.action === "none" ? ` (${decision.why})` : ""} · now=${leadNow?.cluster_id ?? "(none)"} ${leadNow?.sources ?? 0} SRC sig ${leadNow?.sig ?? "—"} [${leadNow?.date ?? ""} ${leadNow?.reason ?? ""}] · yesterday=${leadYday?.cluster_id ?? "(none)"}`,
);

// ── Beat 7 · Brief Wire (same rotate-on-crawl-change rule as rank-*.json) ──
const wireLastPath = resolve(dir, "wire-last.json");
const wirePrevPath = resolve(dir, "wire-prev.json");
const wireDataPath = resolve(desk, "src/data/wire.ts");
function readWire(p: string): WireSnapshot | null {
  if (!existsSync(p)) return null;
  try {
    return readWireSnapshot(JSON.parse(readFileSync(p, "utf8")));
  } catch {
    return null;
  }
}
const wireOldLast = readWire(wireLastPath);
let wirePrev = readWire(wirePrevPath);
if (wireOldLast && wireOldLast.crawl_at !== PULSE_CLUSTERS_AT) {
  wirePrev = wireOldLast;
  writeFileSync(wirePrevPath, JSON.stringify(wireOldLast, null, 2) + "\n");
}
const wire = buildWire(PULSE_CLUSTERS, wirePrev, {
  at: cur.at,
  crawlAt: PULSE_CLUSTERS_AT,
  scores,
  tasteIds: X_TASTE.items.map((t) => t.id),
  // The current daily lead is on the Take — never repeated on the Wire (backfills to 5).
  excludeIds: leadNow?.cluster_id ? [leadNow.cluster_id] : [],
});
writeFileSync(wireLastPath, JSON.stringify(wire, null, 2) + "\n");
const wc = wireCounts(wire.rows);
writeFileSync(
  wireDataPath,
  `/** Beat 7 Brief Wire — generated by scripts/rank-snapshot.ts (npm postingest). Multi-source, AI-filtered clusters; never Taste; never displaces the lead. */
import type { WireRow } from "@/lib/wire";

export const WIRE_CRAWL_AT = ${JSON.stringify(wire.crawl_at)};
export const WIRE_PREV_CRAWL_AT: string | null = ${JSON.stringify(wirePrev?.crawl_at ?? null)};
export const WIRE_NEW = ${wc.fresh};
export const WIRE_MOVED = ${wc.moved};

export const WIRE_ROWS: WireRow[] = ${JSON.stringify(wire.rows, null, 2)};
`,
);
console.log(`wire OK ${wireHeader(wire.crawl_at, wire.rows)} prev=${wirePrev?.crawl_at ?? "(none)"} eligible=${wire.order.length}`);
for (const r of wire.rows)
  console.log(`  ${wireMark(r).padEnd(4)} #${r.rank} prev ${r.prev_rank ?? "—"} ${r.sources} SRC ${r.id.padEnd(24)} ${r.title.slice(0, 80)}`);

function leadCandidatesAll(
  clusters: typeof PULSE_CLUSTERS,
  now: number,
  opts: { scores: Record<string, number>; memberAt: Record<string, string>; tasteIds: string[] },
) {
  const wc = buildWire(clusters, null, { at: "", crawlAt: "", scores: opts.scores, tasteIds: opts.tasteIds, max: 99 });
  return wc.rows.map((r) => {
    const c = clusters.find((x) => x.id === r.id)!;
    const first = groupFirstAt(c, opts.memberAt);
    return { ...r, first: new Date(first).toISOString(), ageH: ((now - first) / 3_600_000).toFixed(1), reason: leadExcludeReason(c, now, opts) };
  });
}
