#!/usr/bin/env bun
/**
 * Beat 4 — corroboration rank snapshot. Runs after every real ingest (npm `postingest`).
 * Reads the freshly written data modules, ranks curated Brief/Digest items below the
 * pinned lead, rotates artifacts/sage/rank-last.json → rank-prev.json (only when the
 * crawl stamp changed), writes the new rank-last.json and src/data/corroboration-rank.ts.
 * No HTTP. Exits 1 if the lead is not hf-* (cycle 003 lock).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { DIGEST_ITEMS } from "@/data/digest-pack";
import { PULSE_CLUSTERS, PULSE_CLUSTERS_AT } from "@/data/pulse-clusters";
import { diffSnapshots, rankBelowLead, toSnapshot, type RankSnapshot } from "@/lib/corroboration";

const desk = resolve(import.meta.dir, "..");
const dir = resolve(desk, "artifacts/sage");
const lastPath = resolve(dir, "rank-last.json");
const prevPath = resolve(dir, "rank-prev.json");
const dataPath = resolve(desk, "src/data/corroboration-rank.ts");

function readSnap(p: string): RankSnapshot | null {
  if (!existsSync(p)) return null;
  try {
    const j = JSON.parse(readFileSync(p, "utf8")) as RankSnapshot;
    return j && j.schema === 1 && Array.isArray(j.rows) ? j : null;
  } catch {
    return null;
  }
}

const rows = rankBelowLead(DIGEST_ITEMS, { clusters: PULSE_CLUSTERS, leadId: "hf-incident" });
const lead = rows.find((r) => r.lead);
if (!lead || !/hf/.test(lead.id)) {
  console.error(`rank-snapshot FAIL: lead is ${lead?.id ?? "(none)"} — cycle 003 locks hf-incident`);
  process.exit(1);
}
const cur = toSnapshot(rows, new Date().toISOString(), PULSE_CLUSTERS_AT);

mkdirSync(dir, { recursive: true });
const oldLast = readSnap(lastPath);
let prev = readSnap(prevPath);
if (oldLast && oldLast.crawl_at !== cur.crawl_at) {
  prev = oldLast;
  writeFileSync(prevPath, JSON.stringify(oldLast, null, 2) + "\n");
}
writeFileSync(lastPath, JSON.stringify(cur, null, 2) + "\n");
const moved = diffSnapshots(prev, cur);

const body = `/** Beat 4 corroboration rank — generated by scripts/rank-snapshot.ts (npm postingest). Curated Brief/Digest items only; lead pinned. */
import type { MovedRow, RankSnapshot } from "@/lib/corroboration";

export const RANK_CURRENT: RankSnapshot = ${JSON.stringify(cur, null, 2)};

export const RANK_PREV: RankSnapshot | null = ${JSON.stringify(prev, null, 2)};

export const RANK_MOVED: MovedRow[] = ${JSON.stringify(moved, null, 2)};
`;
writeFileSync(dataPath, body);

console.log(`rank-snapshot OK crawl=${cur.crawl_at} prev=${prev?.crawl_at ?? "(none)"} lead=${cur.lead_id}`);
for (const m of moved) {
  const r = cur.rows.find((x) => x.id === m.id);
  console.log(
    `  ${m.status.padEnd(4)} ${m.id.padEnd(16)} rank ${m.prev_rank ?? "—"}→${m.rank ?? "—"} base ${r?.base_rank ?? "—"} src ${m.prev_sources ?? "—"}→${m.sources ?? "—"} ×${r?.mult ?? "—"}${m.by_corroboration ? " corroboration" : ""}`,
  );
}
