/**
 * Build-time stamps for the static desk page, from src/data/build-stamp.ts — generated by
 * scripts/build-stamp.mjs in `prebuild` (after the CURRENT hard gate). No filesystem reads at
 * request time; a build without the stamp fails to compile (fail closed).
 */
import { BUILD_STAMP } from "@/data/build-stamp";
import type { PauseMap } from "@/lib/source-pause";

export type BuildMeta = {
  buildId: string;
  builtAt: string;
  /** Source commit (CF_PAGES_COMMIT_SHA → git rev-parse). */
  commit: string;
  /** Crawl commit (SAGE_CRAWL_COMMIT → last commit touching artifacts/sage/CURRENT.json). */
  crawlCommit: string;
  /** Public repo URL for footer commit links. */
  repoUrl: string;
  cycleId: string;
  compiledAt: string;
  crawledAt: string;
  /** Active source pauses merged from artifacts/sage/source-state.json at prebuild. */
  pauses: PauseMap;
};

export const BUILD_META: BuildMeta = { ...BUILD_STAMP, pauses: { ...(BUILD_STAMP.pauses as PauseMap) } };
