/**
 * OPT win 3 (caps) — renders src/data/desk-view.ts and enforces DESK_VIEW_CAPS.gzBytes on it.
 * Scripts + tests only (node:zlib) — the desk client never imports this file.
 * fitDeskView(): row + field caps first (buildDeskView), then the smallest number of extra oldest unpinned stories
 * dropped so that gzip -9 of the rendered module ≤ gzBytes. Deterministic: same input ⇒ byte-identical module.
 */
import { gzipSync } from "node:zlib";
import type { MovedRow, RankSnapshot } from "@/lib/corroboration";
import { buildDeskView, droppableStories, DESK_VIEW_CAPS, type DeskView, type DeskViewCaps, type DeskViewInput, type DeskViewOpts, type SlimLead } from "@/lib/desk-view";
import type { SourceHealthRow } from "@/lib/source-health";
import type { HeatWindow } from "@/lib/topic-heat";
import type { WireRow } from "@/lib/wire";

export type DeskViewStamps = {
  CRAWL_AT: string;
  PULSE_CLUSTERS_AT: string;
  SOURCE_HEALTH_AT: string;
  WIRE_CRAWL_AT: string;
  WIRE_PREV_CRAWL_AT: string | null;
  TOPIC_HEAT_AT: string;
};
/** The small crawl-written modules carried as-is (their producers bound them). */
export type DeskViewExtras = {
  stamps: DeskViewStamps;
  LEAD_HELD: boolean;
  LEAD_FIRST_AT: string | null;
  LEAD_TODAY: SlimLead | null;
  LEAD_YESTERDAY: SlimLead | null;
  RANK_CURRENT: Omit<RankSnapshot, "at">;
  RANK_PREV: Omit<RankSnapshot, "at"> | null;
  RANK_MOVED: readonly MovedRow[];
  WIRE_ROWS: readonly WireRow[];
  TOPIC_HEAT_WINDOWS: readonly HeatWindow[];
  SOURCE_HEALTH: readonly SourceHealthRow[];
  SHELF: readonly { href: string; label: string; reason: string }[];
};

export const gzBytes = (s: string) => gzipSync(s, { level: 9 }).length;

const j = (v: unknown) => JSON.stringify(v);
/** One array element / object entry per line: readable diffs, no pretty-print bloat. */
const lines = (arr: readonly unknown[]) => (arr.length ? `[\n${arr.map((v) => `  ${j(v)},`).join("\n")}\n]` : "[]");
const entries = (o: Record<string, unknown>) => {
  const e = Object.entries(o);
  return e.length ? `{\n${e.map(([k, v]) => `  ${j(k)}: ${j(v)},`).join("\n")}\n}` : "{}";
};

/** Cluster ids the other crawl modules reference — pinned so nothing the desk renders can point at a dropped story. */
export function deskViewPins(x: DeskViewExtras): string[] {
  const ids = new Set<string>();
  for (const w of x.WIRE_ROWS) ids.add(w.id);
  for (const s of [x.RANK_CURRENT, x.RANK_PREV]) for (const r of s?.rows ?? []) for (const h of r.crawl_hits ?? []) ids.add(h);
  for (const l of [x.LEAD_TODAY, x.LEAD_YESTERDAY]) if (l?.cluster_id) ids.add(l.cluster_id);
  return [...ids].sort();
}

export function renderDeskViewModule(view: DeskView, x: DeskViewExtras): string {
  const s = x.stamps;
  return `/**
 * Slim client view of crawl ${s.PULSE_CLUSTERS_AT} — GENERATED by scripts/desk-view.ts (run by rank-snapshot / npm postingest).
 * Do not edit. The desk imports crawl data ONLY from here; raw src/data modules stay for scripts and tests.
 * pages-coherence: DESK_VIEW_AT must equal CRAWL_AT (x-crawl) = PULSE_CLUSTERS_AT = WIRE_CRAWL_AT = TOPIC_HEAT_AT.
 * Size is fixed by DESK_VIEW_CAPS (src/lib/desk-view.ts): gzip -9 of this file ≤ ${DESK_VIEW_CAPS.gzBytes} B.
 */
import type { MovedRow, RankSnapshot } from "@/lib/corroboration";
import type { DeskViewTrim, MemberRow, OrphanCluster, SlimLead, XRef } from "@/lib/desk-view";
import type { SourceHealthRow } from "@/lib/source-health";
import type { HeatWindow } from "@/lib/topic-heat";
import type { WireRow } from "@/lib/wire";

export const DESK_VIEW_AT = ${j(s.PULSE_CLUSTERS_AT)};
export const CRAWL_AT = ${j(s.CRAWL_AT)};
export const PULSE_CLUSTERS_AT = ${j(s.PULSE_CLUSTERS_AT)};
export const SOURCE_HEALTH_AT = ${j(s.SOURCE_HEALTH_AT)};
export const WIRE_CRAWL_AT = ${j(s.WIRE_CRAWL_AT)};
export const WIRE_PREV_CRAWL_AT: string | null = ${j(s.WIRE_PREV_CRAWL_AT)};
export const TOPIC_HEAT_AT = ${j(s.TOPIC_HEAT_AT)};

/** What DESK_VIEW_CAPS left out of this crawl (counts only). */
export const DESK_VIEW_TRIMMED: DeskViewTrim = ${j(view.trimmed)};

export const LEAD_HELD: boolean = ${j(x.LEAD_HELD)};
export const LEAD_FIRST_AT: string | null = ${j(x.LEAD_FIRST_AT)};
export const LEAD_TODAY: SlimLead | null = ${j(x.LEAD_TODAY)};
export const LEAD_YESTERDAY: SlimLead | null = ${j(x.LEAD_YESTERDAY)};

export const RANK_CURRENT: Omit<RankSnapshot, "at"> = ${j(x.RANK_CURRENT)};
export const RANK_PREV: Omit<RankSnapshot, "at"> | null = ${j(x.RANK_PREV)};
export const RANK_MOVED: MovedRow[] = ${lines(x.RANK_MOVED)};

export const WIRE_ROWS: WireRow[] = ${lines(x.WIRE_ROWS)};

export const TOPIC_HEAT_WINDOWS: HeatWindow[] = ${lines(x.TOPIC_HEAT_WINDOWS)};

export const SOURCE_HEALTH: SourceHealthRow[] = ${lines(x.SOURCE_HEALTH)};

/**
 * One record per crawl item + X post: b badge · p publisher · t title · a time · u url · s signal · m summary · sec ·
 * dt drawer title · c the Pulse cluster this item leads (cluster leads come first, in cluster order). See src/lib/desk-view.ts.
 */
export const MEMBER_ROWS: Record<string, MemberRow> = ${entries(view.memberRows)};

/** Clusters whose lead is not a crawl item (normally empty). */
export const ORPHAN_CLUSTERS: OrphanCluster[] = ${lines(view.orphanClusters)};

/** Operator X posts: take = head (n chars) of the x: member summary, link = its url (see XRef). */
export const X_POSTS: XRef[] = ${lines(view.xPosts)};

/** Pass A2: Papers rows live in desk-view-papers.ts (not re-exported here, or they would ride back into First Load). */

export const SHELF: { href: string; label: string; reason: string }[] = ${lines(x.SHELF)};
`;
}

/** Pass A2: src/data/desk-view-papers.ts — PAPERS only, loaded by the Papers lane via dynamic import(). Row/field capped. */
export function renderDeskViewPapersModule(view: DeskView, x: DeskViewExtras): string {
  return `/**
 * Papers lane rows of crawl ${x.stamps.PULSE_CLUSTERS_AT} — GENERATED by scripts/desk-view.ts with desk-view.ts. Do not edit.
 * Lazy chunk: the desk imports this only when the Papers lane opens, so it is outside First Load (and outside gzBytes).
 */
import type { PaperInput } from "@/lib/pulse-v5";

export const PAPERS: PaperInput[] = ${lines(view.papers)};
`;
}

export type FitResult = { view: DeskView; body: string; gz: number; drop: number };

/** Row + field caps, then the fewest extra oldest stories dropped so the module fits gzBytes (then oldest papers / X posts if pins alone overflow). Throws if it cannot. */
export function fitDeskView(input: DeskViewInput, extras: DeskViewExtras, opts: Omit<DeskViewOpts, "drop"> = {}): FitResult {
  const budget = (opts.caps ?? DESK_VIEW_CAPS).gzBytes;
  const pins = deskViewPins(extras);
  const inp = { ...input, pins };
  const at = (drop: number): FitResult => {
    const view = buildDeskView(inp, { ...opts, drop });
    const body = renderDeskViewModule(view, extras);
    return { view, body, gz: gzBytes(body), drop };
  };
  const first = at(0);
  if (first.gz <= budget) return first;
  // Smallest drop that fits (binary search; size falls as stories go). Pinned stories + fixed parts must fit alone.
  let lo = 1;
  let hi = droppableStories(inp, opts);
  let best = at(hi);
  if (best.gz > budget) {
    // Pins + fixed lanes alone are over budget (only reachable with pathological input, e.g. every pinned link at
    // LINK_MAX = 2048 random chars): every unpinned story is already gone, so shed the oldest papers, then the oldest
    // operator X posts, until it fits. Pinned stories are never dropped; the budget stays the bound on total size.
    const caps: DeskViewCaps = opts.caps ?? DESK_VIEW_CAPS;
    const atCaps = (c: DeskViewCaps): FitResult => {
      const view = buildDeskView(inp, { ...opts, caps: c, drop: hi });
      const body = renderDeskViewModule(view, extras);
      return { view, body, gz: gzBytes(body), drop: hi };
    };
    // Pass A2: papers live in desk-view-papers.ts (lazy chunk) and no longer count toward gzBytes — shed X posts only.
    for (let x = caps.xPosts - 1; x >= 0 && best.gz > budget; x--) best = atCaps({ ...caps, xPosts: x });
    if (best.gz > budget) throw new Error(`desk-view: ${best.gz} B gz > budget ${budget} B with only pinned stories left and no X posts`);
    return best;
  }
  while (lo < hi) {
    const mid = (lo + hi) >> 1;
    const r = at(mid);
    if (r.gz <= budget) {
      best = r;
      hi = mid;
    } else lo = mid + 1;
  }
  return best.drop === lo ? best : at(lo);
}
