/**
 * Renders src/data/lead-log-view.ts — the holotape log, capped (LEAD_LOG_CAPS), built from
 * artifacts/sage/lead-history.json by scripts/desk-view.ts. lead-history.json stays the full rebuildable record;
 * app/page.tsx imports only this slim view. Scripts + tests only.
 */
import { buildLeadLog, slimLeadLog } from "@/lib/lead-log";

export function renderLeadLogModule(history: unknown): string {
  const log = slimLeadLog(buildLeadLog(history));
  return `/**
 * Holotape lead log — GENERATED by scripts/desk-view.ts from artifacts/sage/lead-history.json (slimLeadLog: only what
 * the tape renders, capped by LEAD_LOG_CAPS in src/lib/lead-log.ts). Do not edit. app/page.tsx passes it as props.
 */
import type { LeadLog } from "@/lib/lead-log";

export const LEAD_LOG: LeadLog = {
  lastAt: ${JSON.stringify(log.lastAt)},
  days: ${log.days.length ? `[\n${log.days.map((d) => `    ${JSON.stringify(d)},`).join("\n")}\n  ]` : "[]"},
};
`;
}
